### PR TITLE
Fixes #912: Make color and effects of loklak similar to Google

### LINKED ISSUE #912: Make color and effects of loklak similar to Google
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**

Few parts of the UI of loklak use color code ```#333``` which was used by Google earlier, now it has been updated to ```#222```. Google also uses hover text as ```Search``` for input field unlike loklak.

**Expected behavior:**

The above mentioned enhancement should be added into loklak.

**Screenshots of the issue:**

### PR DESCRIPTION
**Pull request by simsausaurabh**
**Changes proposed in this pull request**
- Updated color theme similar to Google.
- Added hover title text for input field as ```Search``` similar to Google.

**Screenshots (if appropriate)** 

**Link to live demo: http://pr-913-fossasia-loklaksearch.surge.sh**

**Closes #912**
Addresses: #433

### CODE REVIEW

**Comment by praveenojha33** [comment]
@simsausaurabh Please add an image of the changes, I am unable to figure out which component's color you are modifying.

**Review by praveenojha33 — COMMENTED** [review]
@simsausaurabh Please add an image of the changes, I am unable to figure out which component's color you are modifying.

**Comment by simsausaurabh** [comment]
screenshot from 2018-08-19 14-57-25

The body background color earlier in the project was ```rgb(51,51,51)``` or ```#333```, it has been changed to ```#222``` similar to Google.

@praveenojha33 Please review.

**Review by praveenojha33 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
