### PR TITLE
fixes #915: Shift Profile section above Top Twitterers and Top hashtags

### LINKED ISSUE #915: Shift Profile section above Top Twitterers and Top hashtags
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

Currently whenever a search is made using `from: user_name` the profile section of the user appears below the top twitterers and top hashtags section.Since its results are more relevant it should be above Top Twitterers and Top hashtags.
**Expected behavior:**
Please shift Profile section above Top Twitterers and Top hashtags

**Screenshots of the issue:**
image

### PR DESCRIPTION
**Pull request by sakshee-19**
**Changes proposed in this pull request**
-Exchange position of `user-info-box` and `info-box` in file `feed.componenet.html`.

**Screenshots (if appropriate)** 

**Link to live demo: http://pr-920-fossasia-loklaksearch.surge.sh** 

**Closes #915**

### CODE REVIEW

**Comment by sakshee-19** [comment]
@praveenojha33 @simsausaurabh Please review.

**Review by praveenojha33 — APPROVED** [review]
This PR is fine. However We have some more bugs related to responsiveness of profile section and top twitterers . It will be great if you can fix that. Thank You

**Review by simsausaurabh — COMMENTED** [review]
@sakshee-19 The PR is good to go with the replacement of Top Twitters with Top hashtags. You can work on the issues related to responsiveness in your subsequent PRs.

@mariobehling Should we go with this replacement of Top Twitters with Top hashtags section?

**Comment by sakshee-19** [comment]
@simsausaurabh @praveenojha33 Shall I create new issue for the responsiveness of profile section and top twitterers?

**Comment by praveenojha33** [comment]
@sakshee-19 Yeah sure :+1:

**Pull request closed without merging**
