### PR TITLE
Fixes #731: Update travis & docs, and remove automatic deployment to gh-pages branch

### LINKED ISSUE #731: Update travis & docs, and remove automatic deployment to gh-pages branch
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

The new development branch details are not present in docs.

**Expected behavior:**

Branch Policy should be updated in docs.

**Screenshots of the issue:**

Not applicable.

### PR DESCRIPTION
**Pull request by simsausaurabh**
**Changes proposed in this pull request**
- Updated branch policy.
- Updated node and npm version in requirements.
- Updated travis to check builds on development branch.
- Removed deployment to gh-pages.

**Screenshots (if appropriate)** Not Applicable.

**Link to live demo: http://pr-733-fossasia-loklaksearch.surge.sh** 

**Closes #731**

### CODE REVIEW

**Comment by mariobehling** [comment]
Deplpoyment to Github pages should stay. There is no reason to move away from gh-pages.

**Comment by mariobehling** [comment]
You can deploy master to gh-pages and development to heroku for testing, but keep gh-pages, please.

**Comment by simsausaurabh** [comment]
@mariobehling Ok, sorry for that. I am keeping master branch deployment to gh-pages. We need to deploy development on heroku for testing. gh-pages should not have both of these deployments(from master and development). So for creating deployment of development branch to heroku for testing, it requires access to repo. Could you please create a repo on heroku for the same?

**Comment by simsausaurabh** [comment]
@hemantjadon please review.

**Comment by simsausaurabh** [comment]
@mariobehling please review.

**Pull request closed without merging**
