### PR TITLE
Design separate component for speech recognition and embed voice search on results page

### LINKED ISSUE #697: Include voice search on results page
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**

Currently voice search feature is not included on the results page.

**Expected behavior:**

This is a second part of issue[WIP] opened earlier, the voice search feature needs to be included on the results page too. 

**Screenshots of the issue:**

Not applicable.

### PR DESCRIPTION
**Pull request by simsausaurabh**
**Changes proposed in this pull request**
- Created a new component for speech recognition.
- Embedded voice search feature on results page.

**Screenshots (if appropriate)** Not applicable.

**Link to live demo: http://pr-711-fossasia-loklaksearch.surge.sh** 

**Closes #697 #698**

### CODE REVIEW

**Comment by simsausaurabh** [comment]
@mariobehling please review.

**Comment by simsausaurabh** [comment]
@sudheesh001 Thanks for the review.

>Do we really need this to be full page? The UX after search with the small bar showing up seems much nicer.

The featured UX and UI is made similar to the Google's speech recognition featur for voice search. And to make it consistent with the voice search feature in susper.com too.

>In case permission for Microphone isn't given, clicking on the mic button doesn't automatically open up the drop down requesting allow access from the URL bar of the browser.

As it is made similar to the Google, same functionality is provided by Google too. Even when Microphone is not given access, it will show only message to check the microphone and audio levels. It does not show the drop down requesting allow access.

Here:
screenshot from 2018-05-19 09-38-48

**Comment by simsausaurabh** [comment]
@sudheesh001 I agree with you on this. So shall I send another patch for the same after it gets merged or shall I send the changes with this patch only? Since the changes are a lot in one single PR.

**Comment by sudheesh001** [comment]
Sure that's totally fine. Please merge this once another maintainer approves this PR. Good work! 👍

**Comment by simsausaurabh** [comment]
@mariobehling please review. @hemantjadon has not been active for a while.

**Comment by mariobehling** [comment]
Please resolve merge conflicts.

**Comment by simsausaurabh** [comment]
@mariobehling Resolved the conflicts, please merge.

**Pull request merged**
