### PR TITLE
Fixes #931: Security vulnerabilities in some dependencies

### LINKED ISSUE #931: Security vulnerabilities in some dependencies
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

There are some security vulnerabilities in some dependencies.

**Expected behavior:**

It should be fixed asap.

Affected dependencies: ```cryptiles```, ```timespan```, ```url-parse```, ```merge```.

### PR DESCRIPTION
**Pull request by sakshee-19**
**Changes proposed in this pull request**
- Fixed security vulnerabilities using: ```npm fix audit```.

**Screenshots (if appropriate)** 
Before:
screenshot from 2018-11-10 20-13-24

After:
screenshot from 2018-11-10 21-13-55

All 4 high priority security vulnerability is fixed.
**Link to live demo: http://pr-933-fossasia-loklaksearch.surge.sh** 

**Closes #931**

### CODE REVIEW

**Comment by sakshee-19** [comment]
@simsausaurabh @praveenojha33 Please review.

**Review by simsausaurabh — APPROVED** [review]
LGTM :+1: 
It should fix the vulnerabilities, if not then you would have to try ```npm update``` and ```npm install``` to fix moderate vulnerabilities too if possible. Let's see.

**Comment by sakshee-19** [comment]
@simsausaurabh Sure, thank you.

**Review by praveenojha33 — COMMENTED** [review]
Looks Good, Please check the project and all its components after reinstalling the node modules with updated dependencies and make sure everything works normal.

**Comment by sakshee-19** [comment]
@praveenojha33 I have checked it again after removing ```node_modules``` folder and reinstalling updated dependencies with ```npm install``` and everything runs fine:

screenshot from 2018-11-12 22-15-23

screenshot from 2018-11-12 22-15-27

**Comment by sakshee-19** [comment]
@praveenojha33 Please review.

**Review by praveenojha33 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
