### PR TITLE
Followup Fix for #271: Added loading bar and improved info-box display

### LINKED ISSUE #271: Sidebar not working anymore
Please see in screenshot.

screenshot from 2017-02-11 13-17-52

### PR DESCRIPTION
**Pull request by Achint08**
**Fixes #271  : Added loading bar and improved info-box display**

**Changes proposed in this pull request**
- Added loading bar for info-box
-Info-box will be displayed only if retrieved otherwise info-box is hidden
- Made separate reducer for aggregation

**Screenshots (if appropriate)** 

**Link to live demo (if appropriate):** 

Checkout [here](https://achint08.github.io/loklak_search/)

**Closes #271 **

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks, this makes sense. I am unclear how this works though. It seems like the sidebar is just loading eternally if there is no information?

**Comment by Achint08** [comment]
@mariobehling Checkout now. Fixed that.

**Comment by hemantjadon** [comment]
@Achint08 
Separate reducers for the same action, Like I am dispatching a Search Action it apperantly means there is the intent to load aggregations along with the results.

We define reducers on the basis of intent, managing two reducers which effectively do same thing (collecting aggregations) doesn't comply with the structure.

We have to handle 2 requests for the api response (one with `all` and other with `cache` , we can do this in simply the SearchEffect, sending two requests, and then combining the results when bot responses are available and then launching SearchCompleteAction, this will not only streamline the process but also make sure that there is no overlap of intent and multiple reducers working for effectively same thing at once.

**Comment by Achint08** [comment]
@hemantjadon Sure. I will proceed this way.

**Comment by hemantjadon** [comment]
So I guess this PR can be closed for now?

**Comment by Achint08** [comment]
Yeah sure.

**Pull request closed without merging**
