### PR TITLE
Fixes #902: Removed package-lock.json from loklak_search repo

### LINKED ISSUE #902: Fix automatic deployment to gh-pages from master branch
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

Currently there is some discrepancy in automatic deployment from master branch to gh-pages branch.

**Expected behavior:**

It should be fixed by restoring node version in travis.

**Screenshots of the issue:**

### PR DESCRIPTION
**Pull request by praveenojha33**
**Changes proposed in this pull request**
- Removed package-lock.json from loklak_search repo

**Closes #902 **

### CODE REVIEW

**Comment by simsausaurabh** [comment]
@praveenojha33 Will it be favourable to remove it in a long run? Can it be fixed with any other way?

**Comment by praveenojha33** [comment]
@simsausaurabh I think it will not cause any problem as it is regenerated by `npm install` command. It can be used till we find any other solution to fix the issue of deployment(might be by modifying deploy.sh file). Or if you can fix travis for Node Version 6, I think then also it will be fine and I will close this PR.

**Review by singhpratyush — CHANGES_REQUESTED** [review]
Not at all good to merge.

https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

**Review by simsausaurabh — COMMENTED** [review]
@singhpratyush @praveenojha33 Closing this PR, will update the other patch with fixed deployment script.

**Comment by praveenojha33** [comment]
@simsausaurabh :+1:

**Pull request closed without merging**
