### PR TITLE
Fixes #554 : Add "Privacy" Page and link it in Footer

### LINKED ISSUE #554: Add "Privacy" Page and link it in Footer
We need a page for a privacy policy. Use the same style as for "Terms" page. Also do the following:
* Add link "Privacy" in the footer on the right hand side
* Implement the following order: Privacy, Terms, Contact

screenshot from 2017-08-19 16-45-58

### PR DESCRIPTION
**Pull request by ParthS007**
**Changes proposed in this pull request**
- I have added a privacy page and linked it in the footer.

privacy1

privacy0

**Closes #554 **

### CODE REVIEW

**Comment by vibhcool** [comment]
@ParthS007 , if you think this PR isn't reviewable, please replace `Fixes` with `[WIP]` in the heading. If it is open for review, you may add a comment asking to review. 

TravisCI needs to be fixed and all commits need to be squashed to 1. If you need any help just dropin to gitter channel.
cheers!! :)

**Comment by vibhcool** [comment]
to restart the travisCI, login to it, or use `git commit --amend`. opening-closing PR doesn't looks nice :)

**Comment by ParthS007** [comment]
Please review @vibhcool @Achint08 @hemantjadon @mariobehling https://parths007.github.io/loklak_search/

**Comment by mariobehling** [comment]
Thanks!

**Pull request merged**
