### PR TITLE
Infobox UI and logic enhancements

### LINKED ISSUE #252: Info box on top on phone
The task is to display info-box at the top when [idea](https://github.com/fossasia/loklak_search/issues/248) is searched followed by the result.

### LINKED ISSUE #333: Sidebar often does not show up
The sidebar often does not show up even though data is apparently available from api.loklak.org. Investigate the issue and solve it. If the issue is related to loklak server, please open an issue there and solve it.

screenshot from 2017-04-29 15-37-00

### PR DESCRIPTION
**Pull request by hemantjadon**
* Improves the infobox design overall

* Solves the issue of infobox on top on mobile devices

* Fixes the issue of infobox not appearing,
  * Sometimes still the infobox might not appear, as for the queries which are fresh the aggregations are not yet generated by the API thus server returns the blank response as aggregations field.

**Link to live demo (if appropriate):** 
https://hemantjadon.github.io/loklak_search

**Closes #252**
**Closes #333**

### CODE REVIEW

**Comment by vibhcool** [comment]
Design becomes wierd. Upper section is results feed page and lower section is search home page, both on same page 
screenshot from 2017-08-21 18-03-56

**Comment by hemantjadon** [comment]
@vibhcool It was an error related to the deployment, I have fixed it now, please check 😄

**Comment by vibhcool** [comment]
@hemantjadon , please see profiles in the right, they are not viewing images of profiles
screenshot from 2017-08-22 17-53-54

**Comment by hemantjadon** [comment]
@vibhcool This is what I intended to do, This is something I wanted to try, as IMO no images in the sidebar seem bit cleaner to me, actually the size of images is too small to be visible there, and along with the numbers it was not looking cleaner. Also those images were the Images directly taken from twitter, and not from the url provided in the API response

**Comment by vibhcool** [comment]
But this doesn't appears nice to me 😅 . 
you can do something like:
1)  <image> <text> <no.> 
2) or just hide the no.s 
3) or hide the pic for top hashtags and hide numbers for top mentions

**Comment by hemantjadon** [comment]
@vibhcool This all is cool, but what I am trying to say that, the loklak API along with aggregations doesn't provide the image URL, what we were previously doing is  taking the username and appending it in something like `pbs.twimg.com/<username>`, if someday twitter changes this URL to private, or nor CORS, we will not be able to fetch images, Here we are depending on twitter directly instead of loklak backend.
I maybe bit overthinking this, but this is what I thought.

**Pull request closed without merging**
