### PR TITLE
Parent #716: Fix UI bugs in Media-Wall Component

### PR DESCRIPTION
**Pull request by simsausaurabh**
**Changes proposed in this pull request**
- Removed unwanted outlines from buttons on their click.
- Adjusted margin between the buttons. 
- Adjusted the font size.

**Screenshots (if appropriate)** 
1.
screenshot from 2018-05-22 19-13-01

2.
screenshot from 2018-05-22 19-14-49

**Link to live demo: http://pr-717-fossasia-loklaksearch.surge.sh** 

**Closes #**

### CODE REVIEW

**Comment by simsausaurabh** [comment]
@praveenojha33 please review.

**Comment by praveenojha33** [comment]
Unable to open media wall using surge 
image

**Comment by simsausaurabh** [comment]
@praveenojha33 there is some problem with surge, it is unable to open open it. I tried to deploy it locally too, still not working. I am trying another deployment framework.

**Comment by simsausaurabh** [comment]
@praveenojha33 It seems surge is unable to deploy it properly, I have provided screenshots please use it to review if possible.

**Comment by simsausaurabh** [comment]
@mariobehling please review.

**Comment by simsausaurabh** [comment]
@singhpratyush please review, I have made the requested changes.

**Comment by singhpratyush** [comment]
@simsausaurabh: Could you please update the screenshots showing the same? Thanks.

**Pull request merged**
