### PR TITLE
Renamed loklak_banner_206x45.png to logo.png

### PR DESCRIPTION
**Pull request by pranayyelugam**
fixed [#82](https://github.com/fossasia/loklak_search/issues/82)

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you. There are different "alt" tags also. Please use the same alt tag for all image instances/pages with the logo. Please use "loklak social media search engine" as an alt tag.

**Comment by jig08** [comment]
@pranayyelugam Thanks. Squash your commits into one and rename it as `Fixes #8s: <commit message>` to follow dev practices.

**Comment by pranayyelugam** [comment]
@jig08 done

**Comment by mariobehling** [comment]
Thanks!

**Pull request merged**
