### PR TITLE
Fixes #563: Bottom bar visible and color of input changed

### LINKED ISSUE #563: Bottom bar and search box issues on Firefox
The bottom bar on the start page does not show up on Firefox. The search box is not in the expected design on Firefox. Please see the screenshot below.

screenshot from 2017-08-28 11-07-36

### PR DESCRIPTION
**Pull request by Achint08**
**Changes proposed in this pull request**
- Bottom bar visible and color of input changed on firefox

**Link to live demo (if appropriate):** 

https://achint08.github.io/loklak_search/

**Closes #563 **

### CODE REVIEW

**Comment by Achint08** [comment]
@mariobehling @hemantjadon @vibhcool @singhpratyush @djmgit Please review.

**Comment by AnshulMalik** [comment]
I still need to scroll down to see the bar.

**Comment by nikhilrayaprolu** [comment]
@AnshulMalik please provide a screenshot of the issue you are talking about.

**Comment by AnshulMalik** [comment]
This is what I was talking about
half

**Pull request closed without merging**
