### PR TITLE
Fixes #947: fix security vulnerabilities in project

### LINKED ISSUE #947: Security vulnerabilities: cryptiles & timespan
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

There are some security vulnerabilities present in the project related to cryptiles and timespan.

**Expected behavior:**

It should not be present.

**Screenshots of the issue:**

**Will work on the issue??**

No

### PR DESCRIPTION
**Pull request by sakshee-19**
**Changes proposed in this pull request**
- Fixed security vulnerabilities in project using ```npm audit``` and ```npm audit fix```, and updating respective ```@angular-devkit/build-angular``` & ```Karma``` dependency using ```npm install``` in order to fix respective breaking dependency.

**Screenshots (if appropriate)** 

screenshot from 2019-01-05 12-09-19

**Link to live demo: http://pr-949-fossasia-loklaksearch.surge.sh** 

**Closes #947**

### CODE REVIEW

**Comment by sakshee-19** [comment]
@simsausaurabh @praveenojha33 please review.

**Review by simsausaurabh — CHANGES_REQUESTED** [review]
Did you test after removing node_modules following ```npm install```, if its working fine and there are no breaking changes?

**Comment by sakshee-19** [comment]
@simsausaurabh I have tested it again after removing ```node_modules``` folder and following it: ```npm install``` and it is working fine:

screenshot from 2019-01-07 21-50-25

screenshot from 2019-01-07 21-50-35

**Review by simsausaurabh — APPROVED** [review]

**Review by praveenojha33 — APPROVED** [review]

**Review by shreyanshdwivedi — APPROVED** [review]

**Comment by praveenojha33** [comment]
@sakshee-19 Can you make a PR for Susper also. There are some security vulnerabilities in webpack-dev-server.

**Comment by sakshee-19** [comment]
@praveenojha33 Yes, surely. I will do that. 👍

**Pull request merged**
