### PR TITLE
Made the reply, retweet and like work

### PR DESCRIPTION
**Pull request by Elgayar**
I have added a feature where the user will be able to interact with
tweets from within the loklak search engine! Now, users can like,
retweet and reply easily.
Solves issue: #161

### CODE REVIEW

**Comment by Elgayar** [comment]
@hemantjadon I don't understand: Make this the function and use (click) event bindings

**Comment by Elgayar** [comment]
I'm uploading the website on my gh-pages, I'll send it once it's done.

**Comment by hemantjadon** [comment]
@Elgayar you have used `onclick`, you can use `(click)="handleRetweet($event)"`, Infact why you want to open the link in the small window? let them be simple links, with `target="_blank"`. I don't think opening in small window should be done, not mobile friendly and responsive.

**Comment by Elgayar** [comment]
Ok, I won't make it target="_blank", I made it like that, because in most websites that use the Twitter API, a popup opens when you click like, retweet or reply.

I'll make the target blank!

**Comment by hemantjadon** [comment]
Give gh-pages link so we can test and merge.

**Comment by Elgayar** [comment]
It's showing me an error when I deploy, please give me some time and I'll fix it.

**Comment by Elgayar** [comment]
https://elgayar.github.io/loklak_search/

FINALLY! :joy: @hemantjadon

**Comment by Elgayar** [comment]
image

**Comment by Elgayar** [comment]
Can you please take a look? @hemantjadon

**Comment by mariobehling** [comment]
Only works for me, if I click on icons on the page itself, but clicking on the pop-up tweet itself does not work yet. Please check.

**Comment by Elgayar** [comment]
https://elgayar.github.io/loklak_search @mariobehling Please check now :)

**Comment by mariobehling** [comment]
Good job!

**Comment by Elgayar** [comment]
Thank you! @mariobehling

**Pull request merged**
