### PR TITLE
Fix #203: Add infobox for from:user search

### LINKED ISSUE #203: Implement relevant sidebars for search of from:user
The sidebar displays relevant information for standard searches. For searches of tweets "from:user" the sidebar should display info of the user account. Which relevant info can we get from the loklak APIs? Which sidebars can be implemented? Please propose and implement suitable sidebars showing user account information.

screenshot from 2017-01-11 11-58-39

### PR DESCRIPTION
**Pull request by uttu357**
- User info is fetched separately from the main search so as to not slow it down
- Show basic account information in the info-box
- Implement google theme for info-box
screenshot from 2017-01-27 17 32 14
screenshot from 2017-01-27 17 33 44

Changes are live at https://uttu357.github.io/loklak_search/search?query=from%3Aheroku
Closes #203

### CODE REVIEW

**Comment by mariobehling** [comment]
Good job!

The picture of the account is stretched and ratio changed, but this might also depend on the available picture on twitter. How to solve this?

screenshot from 2017-01-27 14-15-15

**Comment by uttu357** [comment]
screenshot from 2017-01-27 19 40 54
@mariobehling Please see if this is better?

**Comment by rishiraj824** [comment]
@uttu357 Nice work!
A little design suggestion though - I was wondering if we could have some kind of a box-shadow around the profile picture of the user so as to differentiate between the cover photo and the profile picture. I see that there is a white border as of now,  but for an image like this below, it could be improved. What do you think?

**Comment by mariobehling** [comment]
@rishiraj824 

> I see that there is a white border as of now, but for an image like this below, it could be improved.

White border is the same as in twitter. So, probably fine. Additional changes should go into following PRs. Only real issues should be fixed in PRs, so we can progress quickly by iterating.

Issue here: Image is not scaled or cropped, but stretched in wrong ratio. Maybe you can help with fixing that.

**Comment by mariobehling** [comment]
If you like there is a follow up issue here: https://github.com/fossasia/loklak_search/issues/245

**Pull request merged**
