### PR TITLE
Fixes #666: Implement Accounts Using Firebase

### LINKED ISSUE #666: Implement Accounts using Firebase
As we did not have enough resources to set up our own accounting Firebase seems like a good solution to move forward.

Please implement an accounts system using Firebase. Use the free tier of Firebase to start with.

### PR DESCRIPTION
**Pull request by simsausaurabh**
- Implemented accounts using firebase

**Screenshots (if appropriate)** 
- Firstly checked for both anonymous login and twitter, later changed to login only through twitter:
screenshot from 2018-03-09 14-36-26

- Login using oauth- to connect to firebase(account in firebase authentication):
screenshot from 2018-03-09 14-35-54

**Link to live demo: http://pr-794-fossasia-loklaksearch.surge.sh**

**Closes #666**

### CODE REVIEW

**Comment by simsausaurabh** [comment]
@singhpratyush @hemantjadon @praveenojha33 Please review.

**Comment by simsausaurabh** [comment]
There are small issues in travis, I am fixing it :+1: .

**Comment by simsausaurabh** [comment]
@mariobehling @singhpratyush @praveenojha33 Please review. I have implemented basic firebase authentication and login.

**Comment by praveenojha33** [comment]
image
please keep some more distance between service box and sign in button.

**Comment by praveenojha33** [comment]
After a user is logged in Please can we have its username and profile picture displayed like this
image

**Comment by simsausaurabh** [comment]
@praveenojha33 It is a basic setup, it will be implemented further.

**Comment by praveenojha33** [comment]
Good Work :tada ,let others review and provide their suggestions @hemantjadon @singhpratyush @mariobehling Please review.

**Comment by singhpratyush** [comment]
@simsausaurabh: The login flow seems to work properly. Please make the pointer turn into cursor when on signin/signout button. Also, add some css to make a better hover effect on the button, e.g. a shadow.

**Comment by simsausaurabh** [comment]
@singhpratyush Please review, I have made some CSS for the requested changes.

**Pull request merged**
