### PR TITLE
#61 and adjusted the image-banner in about.component.html

### PR DESCRIPTION
**Pull request by pranayyelugam**
issue [#61](https://github.com/fossasia/loklak_search/issues/61)
@mariobehling check this.

### CODE REVIEW

**Comment by mariobehling** [comment]
@pranayyelugam Thank you! Please state in the description the issue. So, it is easily clickable by reviewers. Do you have a sample site on your github, where we can see the changes?

**Comment by pranayyelugam** [comment]
@mariobehling added the issue in the description. I don't have a sample site . would you like me create one? or screenshots would be okay?

**Comment by mariobehling** [comment]
@pranayyelugam Thank you. Quick way should be if you add it to a repo at gh-pages. There are also merge conflicts at the moment. Please check.

**Comment by pranayyelugam** [comment]
@mariobehling Thank you . I will check.

**Pull request closed without merging**
