### PR TITLE
#93 home-page design changes

### PR DESCRIPTION
**Pull request by rishiraj824**
@hemantjadon Here's the one commit for the requisite change. Kindly merge the same. Thank You.

### CODE REVIEW

**Comment by hemantjadon** [comment]
@rishiraj824 The Loklak search button can be removed I guess and can be replaced with a banner **Loklak Search!**.
The all the things can be centered and the cow size can be increased a bit. Maybe (120px X auto).

**Comment by rishiraj824** [comment]
@hemantjadon Banner fixed. The header 'Loklak Search' is very much there and there isn't any button, please check.

**Comment by hemantjadon** [comment]
This is how I am seeing this right now 
screen shot 2016-12-19 at 5 52 34 pm

**Comment by rishiraj824** [comment]
It's not deployed with the latest changes that's why. Here's the screenshot of the current code - with the banner and without the button. @hemantjadon 
ca6c1b16-c553-11e6-87af-d0135f4d412c
ca37ee36-c553-11e6-8555-d26240034178

**Comment by hemantjadon** [comment]
Can you please deploy it So that I can check ?

**Comment by rishiraj824** [comment]
ok sure.

**Comment by rishiraj824** [comment]
@hemantjadon Here you go http://rishiraj.co/loklak_search/

**Comment by mariobehling** [comment]
@rishiraj824 Thank you. Please slightly decrease the space below "Loklak Search".

**Comment by mariobehling** [comment]
Please also change the font of "Loklak Search!" to Courier New (same as on the current loklak.org page).

**Comment by maitreyav** [comment]
I think it looked more apt without "Search". Everyone is already aware about that.

**Comment by hemantjadon** [comment]
@mariobehling Using web fonts can severely slowdown the page load that too for just one line.

As the normal `sans-serif` is the more readable (conventional) for normal text google itself uses `arial` or `sans-serif` and not `Roboto` for the same reason.

**Comment by rishiraj824** [comment]
@mariobehling  Will decrease the space. Also, I agree with @maitreyav. There's no need of putting Loklak Search as people would know that. Let me know what changes to make.

**Comment by rishiraj824** [comment]
- Added Courier New Font
- decreased the space below Loklak Search.
-hosted  [here on github pages](http://rishiraj.co/loklak_search)

**Comment by mariobehling** [comment]
@rishiraj824 Thanks. Let's go with this. Very good job!

**Comment by rishiraj824** [comment]
@mariobehling and @hemantjadon I guess this was merged in the main website. Did you guys rolled back the design. Please let me know if there was any issue.

**Comment by hemantjadon** [comment]
@rishiraj824 I am able to see the new design

**Pull request merged**
