### PR TITLE
Adding lightbox

### LINKED ISSUE #105: Improve message lightbox.
Currently the link area of a tweet opens the actual tweet at twitter. The expected behavior would rather be to open a lightbox (just like twitter), that brings the user back to the search page.

* [x] Please implement a simple overlay lightbox with the tweet info
* [x] Autolinking the text in the cards #141.
* [ ] Responsive UI design of message lightbox #142.
* [ ] In the bottom area show a link with "View at Twitter" (This should be generic, e.g. as we are adding YouTube this should show "View at YouTube" if the source is YouTube)

screenshot from 2016-11-04 03 39 49

### PR DESCRIPTION
**Pull request by Heredroky**
Fixes #105 

You can see a preview here: https://heredroky.github.io/loklak_search/loklak_searchsearch?query=obama

@hemantjadon @mariobehling

### CODE REVIEW

**Comment by mariobehling** [comment]
Checks failing. Please have a look.

**Comment by hemantjadon** [comment]
Check your base href it should be `/loklak_search/` instead of `loklak_search` :)

**Comment by Heredroky** [comment]
@mariobehling Now it has no fail 😄

**Comment by mariobehling** [comment]
Good job!

**Pull request merged**
