### PR TITLE
fix(settings.component.html): Added links to the corresponding text

### LINKED ISSUE #957: Text instead of link in settings menu
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

In the settings menu there must be links present instead of text for the urls. 
**Expected behavior:**

Clicking on the given link would redirect to its url.
**Screenshots of the issue:**

loklak_setting
loklak_setting1
loklak_setting2
loklak_setting3

**Will work on the issue??**

Yes

### PR DESCRIPTION
**Pull request by kpulkit29**
**Changes proposed in this pull request**
- Added links to the corresponding text in the settings

**Screenshots (if appropriate)** 

Screen Shot 2019-08-29 at 10 00 27 PM
**Link to live demo**: http://pr-963-fossasia-loklaksearch.surge.sh 

**Closes #957 **

### CODE REVIEW

**Review by rajvaibhavdubey — CHANGES_REQUESTED** [review]
You don't need to push package-lock.json. Rest LGTM :+1:

**Comment by kpulkit29** [comment]
Sure will remove it

**Review by kushthedude — CHANGES_REQUESTED** [review]
Only push changes related to your pull request. Please read more about Git before making any PRs

**Comment by kpulkit29** [comment]
@kushthedude The only file in PR is the one I changed. I guess that is the only change related to my PR

**Review by mariobehling — APPROVED** [review]

**Comment by kushthedude** [comment]
@mariobehling Please revert the PR also removes package.json which is an unpushed change.
@kpulkit29 only had to change 4 lines rather than 13000 lines

**Comment by kushthedude** [comment]
> @kushthedude The only file in PR is the one I changed. I guess that is the only change related to my PR

Please explain why did you remove package.json

**Pull request merged**
