### PR TITLE
Adding lightbox

### LINKED ISSUE #105: Improve message lightbox.
Currently the link area of a tweet opens the actual tweet at twitter. The expected behavior would rather be to open a lightbox (just like twitter), that brings the user back to the search page.

* [x] Please implement a simple overlay lightbox with the tweet info
* [x] Autolinking the text in the cards #141.
* [ ] Responsive UI design of message lightbox #142.
* [ ] In the bottom area show a link with "View at Twitter" (This should be generic, e.g. as we are adding YouTube this should show "View at YouTube" if the source is YouTube)

screenshot from 2016-11-04 03 39 49

### PR DESCRIPTION
**Pull request by Heredroky**
Fixes #105

### CODE REVIEW

**Comment by Heredroky** [comment]
screen shot 2016-12-16 at 6 34 48 pm
s/15079370/21281903/76923a2a-c3be-11e6-9458-53c22eca41ef.png)

This is a preview

**Comment by hemantjadon** [comment]
It will be graeat if you could deploy this on your gh-pages and give us a link so we can preview.

**Comment by Heredroky** [comment]
@hemantjadon Thanks! I will deploy it and will send the link later 😄

**Comment by mariobehling** [comment]
@Heredroky Thank you. Please also ensure equal padding around tweets. On your second screenshot I see little space on the right hand side of the tweet.

**Comment by Heredroky** [comment]
I will reopen this PR

**Pull request closed without merging**
