### PR TITLE
Added InfoBox #92

### PR DESCRIPTION
**Pull request by rishiraj824**
screenshot 43
screenshot 42

Need help in the following
- Convert the respective lists into tabs
- Add queryParams for the Hashtags and Mentions
- Content doesn't change when the input changes
- Mobile View design needs to be added

site hosted at [rishiraj.co/loklak_search](http://rishiraj.co/loklak_search)
Please have a look @hemantjadon and @mariobehling

### CODE REVIEW

**Comment by mariobehling** [comment]
@rishiraj824 Nice work!

Please ensure travis builds are working.

Let's iterate step by step. Please open a new issue for the next steps.

**Comment by mariobehling** [comment]
> Convert the respective lists into tabs

I think no need for tabs. This is even cleaner.

Right now, just help to make travis work, please. Thank you!

**Comment by Achint08** [comment]
hey @rishiraj824 Travis is failing because you haven't created infoboxstubcomponent in feed.component.spec.ts and declared it. Do it. Checks will pass.

**Comment by rishiraj824** [comment]
@Achint08 can you help me fix the InfoBoxStubComponent. I have added it still shows the error. Also the query doesn't change the InfoBox results.

**Comment by Achint08** [comment]
hey @rishiraj824 You don't need to test infobox in feed-component.spec.ts. You just need to create a info box stub component and declare it in declarations. That's it.

**Comment by rishiraj824** [comment]
@Achint08 Thanks 👍. 

@mariobehling tests are passing now.

**Comment by mariobehling** [comment]
@rishiraj824 Unfortunately there are merger conflicts, that happened in the meantime. Please help to resolve them. Thank you!

**Comment by rishiraj824** [comment]
@mariobehling Fixed the conflicts.

**Pull request merged**
