### PR TITLE
Fixes #521: Direct URL for media wall

### LINKED ISSUE #521: Implementing Direct URLs for media wall
Idea is to implement direct URLs for media wall with the saved customization.

### PR DESCRIPTION
**Pull request by Achint08**
**Changes proposed in this pull request**
- Direct URL for media wall

**Link to live demo (if appropriate):** 

https://achint08.github.io/loklak_search/wall?query=%23trump

**Closes #521**

### CODE REVIEW

**Comment by Achint08** [comment]
@mariobehling @hemantjadon @singhpratyush @vibhcool @kavithaenair @djmgit Please review.

**Comment by Achint08** [comment]
@hemantjadon just forgot to encode in URI format. That's why queries with hashtags was not parsed to URI format.
Check out now.
https://achint08.github.io/loklak_search/wall?query=%23trump

**Comment by mariobehling** [comment]
Thanks!

**Comment by mariobehling** [comment]
Further testing shows that this feature is not thought-through sufficiently. I need to revert this.

What happens if different users use the same search term? You would be generating the same URL?
I see a search of "Trump" generates the media wall http://loklak.org/wall?query=trump Common searches like this one will result in the same URL of different users, who can then customize different walls. This does not make sense. @hemantjadon This approach needs to be reverted. A suitable approach would be a) store all properties of the media wall in the URL (e.g. style, color, search term) and b) provide a short URL. This approach is followed by Google maps for example.

If an anonymous user creates a wall all properties/settings of this wall should stay even if it is opened in another browser or another PC. With your approach this is not given.

**Pull request merged**
