### PR TITLE
Fix #293 - Use single request to fetch results

### LINKED ISSUE #287: Queries getting
For my first query I get "No results found" quite often. The second query then gives me the results.

Please ensure the first query is not failing.

screenshot from 2017-03-14 12-58-12

### LINKED ISSUE #293: Have single requests for Search and Aggregations
Now that using `source=all` parameter in the query gives us the aggregations, we can have one single reducer and only one query request for getting both the aggregations and the tweets. 

[http://api.loklak.org/api/search.json?q=fossasia&source=all](http://api.loklak.org/api/search.json?q=fossasia&source=all)

### PR DESCRIPTION
**Pull request by uttu357**
**Changes proposed in this pull request**
- Remove aggregation service from the source 
- Handle search using the search service

**Closes #293, closes #287**

### CODE REVIEW

**Comment by Achint08** [comment]
Can you give link to gh-pages to check out if this issue is resolved?

**Comment by uttu357** [comment]
@Achint08 Deployed here https://uttu357.github.io/loklak_search/

**Comment by Achint08** [comment]
@uttu357 Well done. :)

**Comment by mariobehling** [comment]
@Achint08 #272 is still unresolved. Cheers.

**Pull request merged**
