### PR TITLE
Fixes #563 Bottom bar is fixed to bottom

### LINKED ISSUE #563: Bottom bar and search box issues on Firefox
The bottom bar on the start page does not show up on Firefox. The search box is not in the expected design on Firefox. Please see the screenshot below.

screenshot from 2017-08-28 11-07-36

### PR DESCRIPTION
**Pull request by AnshulMalik**
Fixes #563 

bottom

### CODE REVIEW

**Comment by nikhilrayaprolu** [comment]
@AnshulMalik great please provide a demo link and "also reference the issue in the body of the pull request. Follow best practices https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

**Comment by AnshulMalik** [comment]
Demo Link @nikhilrayaprolu : https://anshulmalik.github.io/loklak_search/

**Comment by nikhilrayaprolu** [comment]
image

I am not able to receive results please check

**Comment by AnshulMalik** [comment]
Umm, It's because github serves content over https and api calls are over https.

We can temporarily disable that protection by clicking on the shield Icon and then "Disable protection"
It will work fine then.

**Comment by nikhilrayaprolu** [comment]
@AnshulMalik if you look at my screenshot you will find that I have already removed the protection.

**Comment by AnshulMalik** [comment]
Just checked on my end, working fine. How about a refresh?

working

**Comment by nikhilrayaprolu** [comment]
@AnshulMalik  everything looks good now ,please reply to the comment at https://github.com/fossasia/loklak_search/pull/564 so that I could understand what's wrong with the original site.

**Comment by harshit98** [comment]
@AnshulMalik Why are you referencing this PR to #563? Please follow the blog link shared by @nikhilrayaprolu and follow up the best practices. 

Create a separate issue for the scroll bug and refer the PR to it. The fix looks good to me. 👍

**Comment by AnshulMalik** [comment]
@harshit98 This PR is for #563 issue.
Thanks

**Comment by hpdang** [comment]
Thanks!

**Pull request merged**
