### PR TITLE
Added sidebar for Terms page

### LINKED ISSUE #937: Improving Terms and Privacy page UI
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

Currently `Terms` and `Privacy` page is not user friendly at all. We need to improve it by adding sidebar having links to different section.

**Expected behavior:**

We can expect something like Google `Terms` and `Privacy` page.

- [ ] Terms Page
- [ ] Privacy Page

**Screenshots of the issue:**

**Current**
screenshot_2018-12-14 loklak search - distributed search for twitter and social media with peer to peer technology

**Expected**
screenshot_2018-12-12 google terms of service privacy terms google

**Will work on the issue??**

Yes, I'm working on it.

### PR DESCRIPTION
**Pull request by shreyanshdwivedi**
**Changes proposed in this pull request**
- I have added sidebar for `Terms` page to make it more user friendly

**Screenshots (if appropriate)** 
ezgif com-video-to-gif 1

**Surge Link**
http://pr-938-fossasia-loklaksearch.surge.sh/

**Related to #937**

### CODE REVIEW

**Comment by shreyanshdwivedi** [comment]
@praveenojha33 @simsausaurabh pls review. I think codecov is failing bcoz I have added a function in `terms.component.ts` but not added any test for it

**Comment by praveenojha33** [comment]
Please mention this surge link. http://pr-938-fossasia-loklaksearch.surge.sh/

**Review by praveenojha33 — APPROVED** [review]
LGTM :+1:

**Comment by shreyanshdwivedi** [comment]
@simsausaurabh @mariobehling please review

**Review by simsausaurabh — CHANGES_REQUESTED** [review]
@shreyanshdwivedi Please fix:

1. Reduce the left margin of menu which is being fixed, similar to Google.
2. Reduce the margin between the left menu and the content similar to Google.
3. Remove link hovering of left menu similar to Google.

Could it be implemented as a separate component instead of adding more code to the respective component?

**Comment by shreyanshdwivedi** [comment]
@simsausaurabh I've implemented the changes. Also, regarding implementation of this as a component, I don't think it's better idea because we only need it once. It's not reusable in any other part.
Also, we need similar thing for Privacy page too, so it will be redundant if we opt for using two components having similar feature.
Please review. Thanks :)
screenshot_2018-12-19 loklak search - distributed search for twitter and social media with peer to peer technology

**Comment by shreyanshdwivedi** [comment]
@simsausaurabh fixed everything. Please review :)

**Review by simsausaurabh — APPROVED** [review]

**Comment by simsausaurabh** [comment]
Please squash your commits then it will be good to be merged.

**Comment by shreyanshdwivedi** [comment]
@simsausaurabh I've squashed the commits. Please merge it :)

**Pull request merged**
