### PR TITLE
Fix #163 : Simplify Search More style

### LINKED ISSUE #163: Simplify "Search More" style
The "search more" on the bottom introduces a new blue color and has a border element, that we do not find anywhere else on the site. 

Please simplify the style to go inline with the page design
* [ ] Take out the background and border
* [ ] Only show the "Show More" in blue (as it is now) and bold
* [ ] Also ensure the cursor changes when scrolling over

screenshot from 2017-01-03 17-38-52

### PR DESCRIPTION
**Pull request by uttu357**
screenshot from 2017-01-04 00 06 20
Changes are live at https://uttu357.github.io/loklak_search/search?query=javascript

Closes #163

### CODE REVIEW

**Comment by mariobehling** [comment]
@hemantjadon I think, the "Show More" is sufficient. Let's try out this very simple style for some time. Please merge, if code is ok.

**Comment by hemantjadon** [comment]
Okay @mariobehling :)

Merging this as the code seems fine :)

**Comment by mariobehling** [comment]
@hemantjadon After this change I only see 10 search results displayed and "Show More" is not working for me. Any ideas?

**Comment by hemantjadon** [comment]
@mariobehling I am trying recreate the issue but it is working fine for me. Can you please test this again.

**Pull request merged**
