### PR TITLE
Fixes #210 #209

### LINKED ISSUE #210: Display only 20 results on first load
loklak.org displays 20 results on the first search. This results appears rather fast. Please only display 20 results on loklak search itself as well.

### PR DESCRIPTION
**Pull request by Achint08**
Tasks done :- 

1.) Now 20 search results will be shown . fixes #210 
2.) Lightbox is now a component 
3.) Previously suppose there were 20 search feeds then there were 20 lightbox created corresponding to each one. Now a single lightbox is created and its value will be updated through click on feed cards.(using ngrx and reducer functions) Helps in fixing #209 .

gh-pages :- https://achint08.github.io//loklak_search//

Kindly review. :)

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks, please test your changes in more detail, e.g.:
* Lightboxes do not work as expected, e.g. clicking on links does not close box and show new page
* Clicking on some links opens two pages

**Comment by hemantjadon** [comment]
@Achint08 create different PR's for both the issues as they are separate concerns.

**Comment by Achint08** [comment]
Done.Kindly check my gh-pages now
@mariobehling @hemantjadon

**Comment by mariobehling** [comment]
Clicking on links still opens two pages. Clicking on @/hashtags opens lightbox instead of linked item. At times lightbox cannot be closed.

**Comment by Achint08** [comment]
@mariobehling Check out now my gh-pages now please. What issue is there regarding closing of lightbox?

**Comment by mariobehling** [comment]
@Achint08 Very good. The sidebar was updated to reflect new searches already. Looks like you did not pull in the latest changes. Or is there another issue? Cannot see the changes on your gh-pages version.

**Comment by Achint08** [comment]
@mariobehling Damn. I forgot to pull in the recent changes.

**Comment by mariobehling** [comment]
Nice, looks good to me. Thank you!

**Pull request merged**
