### PR TITLE
Fixed #93. Home Page design.

### LINKED ISSUE #93: Implement design changes of start page
* [x] Please ensure the area of the search bar is at around the same area as the Google search bar.
* [x] And slightly decrease the size of the loklak animal to match the logo position of Google
* [x] Ensure the bottom bar already shows up in smaller resolutions (similar to Google)

Please see the difference below. Let's make it more equal.
screenshot from 2016-11-01 15 25 19

### PR DESCRIPTION
**Pull request by rishiraj824**
http://rishiraj.co/loklak_search

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you. Please resolve merge conflicts. Cheers.

**Comment by rishiraj824** [comment]
@mariobehling  Fixed Conflicts for #93

**Comment by hemantjadon** [comment]
@rishiraj824 can you please squash the commits for merging.

According to me the Page seems not symmetrical. As most things are in the upper half. This seems more prominent on mobile also the footer is peeking on small devices which i think should not be the case. What are your views @mariobehling ?

**Comment by hemantjadon** [comment]
@rishiraj824 also why almost all the files are changed?

**Comment by rishiraj824** [comment]
Yeah I'll squash them. And yeah, the files weren't merged properly when I
first pulled the changes so all of them got changed. I'll squash the
commits and review the home page in small screens once again.

**Comment by rishiraj824** [comment]
While squashing I realized, @uttu357 pushed the commits with me, due to which squashing is impossible for me. I can show you the screenshot on my local branch. Also I checked the home-page on Iphone 4 and smaller screen sized devices i'll paste screenshots here, let me know if there are still any issues. And you can squash my commits while merging them I guess. https://github.com/blog/2141-squash-your-commits

**Screenshot at local**
screenshot from 2016-12-18 18 55 22

**Iphone 4 screen -** 
screenshot from 2016-12-18 18 49 58

**Galaxy S5**
screenshot from 2016-12-18 18 50 23

**Comment by hemantjadon** [comment]
well @rishiraj824 this PR will be bit tough to merge, as there are 15 commits and 114 file changes.

Anything which can be done regarding this @mariobehling @jig08 ?

**Comment by rishiraj824** [comment]
one thing I can do is hard reset the forked branch to the state of this repositroy and then push my changes as one commit? @hemantjadon

**Comment by hemantjadon** [comment]
Yes @rishiraj824 you can do that.

**Pull request closed without merging**
