### PR TITLE
Update dependencies

### LINKED ISSUE #262: Out of date dependencies.
Angular and cli have upgraded a lot in past month and I think its right time to upgrade the dependencies. Specially the Angular 2.4 version has a lot if improvements in Component creation and improvement in CLI is useful for generation.

### PR DESCRIPTION
**Pull request by uttu357**
**Changes proposed in this pull request**
- Update angular, angular-cli, zone-js
- Update other dependencies too
- Fix breaking changes

**Link to live demo (if appropriate):https://uttu357.github.io/loklak_search/** 

**Closes #262**

TODO: ng github:deploy no longer works. I have added the dependency to deploy to own gh-pages. Need to update README regarding the new build process.

### CODE REVIEW

**Comment by uttu357** [comment]
@hemantjadon @mariobehling Need to clear the node_modules cached during travis build..

**Comment by mariobehling** [comment]
What to do about travis?

**Comment by mariobehling** [comment]
ok, let's merge and iterate from there.

**Comment by uttu357** [comment]
@mariobehling Travis caches the node_modules so that the builds are faster.. as set in .travis.yml.. As the dependencies have been updated we need to remove the old cached node_modules.. So the travis ci cache for this repository needs to cleared..

**Comment by mariobehling** [comment]
@uttu357 Thanks. I am not familiar with this. Anything do I need to do?

**Comment by uttu357** [comment]
@mariobehling https://travis-ci.org/fossasia/loklak_search/ as you have merge rights hopefully on this page when clicking on more options you would have a option for caches.. On that page there should be an option to delete all caches for this repository..

**Pull request merged**
