### PR TITLE
Fixes #757: Fix broken images on sidebar widget

### LINKED ISSUE #757: Broken images on sidebar
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

Currently the images on sidebar are not appearing.

**Expected behavior:**

The images should be displayed properly.

**Screenshots of the issue:**

screenshot from 2018-06-17 01-15-52

### PR DESCRIPTION
**Pull request by simsausaurabh**
**Changes proposed in this pull request**
- Fix broken images on sidebar widget.
- Start showing the top mentions on sidebar widget.

**Screenshots (if appropriate)** 

screenshot from 2018-06-25 00-05-45

screenshot from 2018-06-25 00-05-51

**Link to live demo: http://pr-780-fossasia-loklaksearch.surge.sh** 

**Closes #757**

### CODE REVIEW

**Comment by simsausaurabh** [comment]
@praveenojha33 Please review.

**Comment by simsausaurabh** [comment]
@praveenojha33 Please review again.

**Comment by praveenojha33** [comment]
Still same issue 
image

**Comment by simsausaurabh** [comment]
@praveenojha33 It works fine for me on Chrome too. There might be some issue with surge or your local cache or may be internet connection.

**Comment by simsausaurabh** [comment]
@praveenojha33 I have updated one change please see if it works for you now.

**Pull request merged**
