### PR TITLE
Update Issue Template

### PR DESCRIPTION
**Pull request by championpaddler**
**Changes proposed in this pull request**
- Updated issue template.
Fixes - #932

### CODE REVIEW

**Comment by championpaddler** [comment]
@simsausaurabh  @rctay  @Orbiter  Please review.

**Review by NaviRocker — APPROVED** [review]
LGTM

**Review by praveenojha33 — CHANGES_REQUESTED** [review]
It does not make much sense to me rather it will complicate the issue template.
@simsausaurabh Please suggest your views.

**Review by simsausaurabh — APPROVED** [review]
It will work for a start, but we would need to remove it in future if it starts creating delay in issue solving process. @sk9331657 There are a lot of priority issues/bugs currently opened, we would be more happy to see work on it.

**Comment by simsausaurabh** [comment]
@sk9331657 Please create an issue for the same and reference the issue here.

**Comment by championpaddler** [comment]
@simsausaurabh  Added issue . Ready to be merged.

**Review by simsausaurabh — APPROVED** [review]

**Pull request merged**
