### PR TITLE
Fixed UI bugs

### LINKED ISSUE #683: UI bugs in Media Wall Design
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
In the Media Wall Design section in the live feed section, there are some UI bugs like:
1. Alignment bugs of the DD menu
2. The corresponding field is going in two lines
3. The font size of the title is less than the subtitle.

**Expected behavior:**
These bugs need to be fixed

**Screenshots of the issue:**
screen shot 2018-03-15 at 11 14 38 pm

I would like to work on this issue 😄

### PR DESCRIPTION
**Pull request by Remorax**
**Changes proposed in this pull request**
- Fixed the alignment-bugs
- Moved the apply button a bit lower so the dropdown menu does not overlap with the button
- Increased the size of the heading as compared to the subheadings

**Screenshots (if appropriate)** 
screen shot 2018-03-16 at 2 10 43 am

**Closes #683 **

### CODE REVIEW

**Comment by prshntsingh** [comment]
@Remorax Please provide preview link. It makes easier to review.

**Comment by prshntsingh** [comment]
@Remorax go through https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/ once. 

As @singhpratyush told me  "The wall won't open up on the demo link because of router issues with Surge." So ,please provide screenshot demonstrating the responsiveness of the element."

**Comment by Remorax** [comment]
I have been through that, I've been contributing to Fossasia for some time, its just my first time at Loklak 😅 
And I've attached the screenshot below 😄 
screen shot 2018-03-18 at 1 57 47 am

**Comment by prshntsingh** [comment]
@remorax. Good, keep contributing. You got it wrong, send the screenshot of the fix you made(changes).So that anyone can review the cahnges.

**Comment by Remorax** [comment]
I'm closing this PR I'll make another one soon!

**Pull request closed without merging**
