### PR TITLE
Travis auto-deploy script and integration search results displaying views

### PR DESCRIPTION
**Pull request by hemantjadon**
* The travis auto deploy script will only work after `deploy key` setup.

* The feed view is in very basic form.

### CODE REVIEW

**Comment by jig08** [comment]
@hemantjadon Thanks.
Could you refer the issue in PR and the commit to which it belongs ? If it doesn't exist, kindly open one.
Also, follow the one commit per issue/PR policy. Cheers !

**Comment by hemantjadon** [comment]
In reference to #12

**Comment by hemantjadon** [comment]
@jig08 
I will take care from the next time that the PR contains the reference to the Issue, apologies for this time.

Both the commits have a pretty different tasks but somehow are related to the same issue i guess, thats why i didn't squashed them.

The first one is a `deploy script` and second one is for `search results` displaying component.

Thanks :)

**Comment by jig08** [comment]
As mentioned, follow the naming pattern of each PR and commit as `Fixes #<issue number> : <commit message>` to keep up with the dev flow of the project and also one commit per PR/Issue.

**Comment by jig08** [comment]
@hemantjadon Change the commit/PR name accordingly pls.

**Comment by mariobehling** [comment]
@hemantjadon Thanks for your work. Please follow best practices in the following pull requests. I am merging this to keep up the speed. Cheers.

**Pull request merged**
