### PR TITLE
Fixes #536: Removes Doubly Hashtags and recovers hashtags in feed link

### LINKED ISSUE #536: Hashtags "##" are showing up twice and cursor not acting as expected
screenshot from 2017-08-14 20-30-53

* Hashtags on a number of areas are showing up twice
* When user goes with the cursor over the result page the cursor does not act as it is supposed to be. Also copying with left side mouse click is not acting as normal

### PR DESCRIPTION
**Pull request by Achint08**
**Changes proposed in this pull request**
- Removes Doubly Hashtags and recovers hashtags in feed link

**Screenshots (if appropriate)** 

screen shot 2017-08-15 at 6 21 58 pm

**Link to live demo (if appropriate):** 
https://achint08.github.io/loklak_search/

**Closes #536 **

### CODE REVIEW

**Comment by hemantjadon** [comment]
@Achint08 this is an error from backend. Solving it here makes no sense. IMO this should be solved at the server @singhpratyush @vibhcool Your views?

**Comment by singhpratyush** [comment]
@hemantjadon: What is this error? What output is different from expected?

**Comment by vibhcool** [comment]
yes, this error should be solved at backend. But there is a need of a sample output with error. @Achint08, please share output screenshot with tweet link so that we can reproduce and backtrack the bug :sweat_smile: . This error appears in rare situations, so a screenshot will be very helpful :)

**Comment by vibhcool** [comment]
just a tweet link will also work fine

**Comment by hemantjadon** [comment]
@vibhcool the error is appearing in every situation, in all aggregations 😅  
See [this](http://api.loklak.org/api/search.json?q=since:2017-08-15_00:00&source=cache&maximumRecords=0&timezoneOffset=-330&startRecord=1&fields=hashtags&limit=10) and [this](http://api.loklak.org/api/search.json?q=since:2017-08-15_00:00&source=cache&maximumRecords=5&timezoneOffset=-330&startRecord=1&fields=hashtags&limit=10) Here as you can see backend is returning all the entities with hash symbol appended, at the start of every string, thus this error.

**Comment by singhpratyush** [comment]
Okay, so the hashtags shouldn't have `#` appended in the beginning. I'll open an issue for this. We can follow up there.

**Comment by Achint08** [comment]
I think this PR should be closed then if it can be solved on the backend overall.

**Pull request closed without merging**
