### PR TITLE
Angular Version Bump to 4.0.0

### PR DESCRIPTION
**Pull request by hemantjadon**
**Changes proposed in this pull request**

* Angular version upgraded to latesst v4

* The dependencies are now up-to-date

### CODE REVIEW

**Comment by hemantjadon** [comment]
Still some Bugs are there Will be fixing them soon.

**Comment by hemantjadon** [comment]
Okay so I investigated here is the reason for the build fail.

* The angular private properties cannot now be accessible from the corresponding templates.

* Here is the link for the issue.
https://github.com/angular/angular/issues/15451#issuecomment-288969991

* Now as in angular v4 this is the case we need to change our all template private variables public. As now `aot` angular compiler produces separate class for both Template and ClassComponent.

* This will require a large code change. (Small bits but a lot of them).

**Comment by hemantjadon** [comment]
@daminisatya @mariobehling 
We will need a lot of code changes for this. Sadly there is no other option apart from making these bulk of changes before upgrading.

**Comment by hemantjadon** [comment]
@daminisatya @mariobehling Please check :)

**Comment by mariobehling** [comment]
Ok, merging it. Let's try.

**Pull request merged**
