### PR TITLE
Fixes #547: Same font size and styles in advanced search

### LINKED ISSUE #547: Different font sizes and styles in same area
Font sizes and alignment in the secondary menu below the search box should be following one implementation similar to Google.

Expected:
screenshot from 2017-08-16 12-41-50

Current Implementation:
screenshot from 2017-08-16 12-41-22

### PR DESCRIPTION
**Pull request by Achint08**
**Changes proposed in this pull request**
- Same font size and styles in advanced search

**Screenshots (if appropriate)** 

screen shot 2017-08-18 at 5 09 27 am

**Closes #547**

### CODE REVIEW

**Comment by hemantjadon** [comment]
@Achint08 Live link please.

**Comment by Achint08** [comment]
@hemantjadon https://achint08.github.io/loklak_search/

**Comment by Achint08** [comment]
@hemantjadon Updated.

**Comment by Achint08** [comment]
@mariobehling Please review.

**Comment by mariobehling** [comment]
Settings and Tools not designed as expected yet.

**Pull request closed without merging**
