### PR TITLE
Addresses #601 Improvements in the UI of suggestion box.

### LINKED ISSUE #601: Improvements in the UI of suggestion box.
- Currently, the UI of suggestion box looks like this:
screen shot 2017-11-15 at 8 38 57 am
It should be equal to the width of the search bar.

- On pressing 'enter' key, the autocomplete box should close. Currently, it is not happening. The user has to wait for it until results are loaded.

### PR DESCRIPTION
**Pull request by ajayns**
**Changes proposed in this pull request**
- Add close suggestion box on pressing return key functionality
- Update UI of search input box (Background made fully white)
- [ Pending ] Match width of suggestion box to search box

**Screenshots (if appropriate)** 
image

**Link to live demo (if appropriate):** 
https://ajayns.github.io/loklak_search/

**Closes #601**

### CODE REVIEW

**Comment by ajayns** [comment]
@harshit98 @ParthS007 I need help on what would be best way to match the width of the suggestion box to the searchbox.

**Comment by ajayns** [comment]
@harshit98 I forgot about the homescreen input box UI and so I've updated that right now. I'm checking the site and it seems to be running fine. The input boxes UI is updated and the suggestions box closes on return key or clicking a suggestion.

**Comment by harshit98** [comment]
@ajayns You can inspect the element. Check `mat-autocomplete-panel` for suggestion box width.

**Comment by ajayns** [comment]
@harshit98 Okay will checkout the panel width right now.

**Comment by ajayns** [comment]
@harshit98 @ParthS007 Also, what can be done to resolve the codecov issue? Any suggestions?

**Comment by harshit98** [comment]
@ajayns Leave codecov issue. Do the the rest of the changes and update the PR name.

**Comment by ajayns** [comment]
@harshit98 @ParthS007 I seem to be having issues adding styling to `mat-autocomplete` component. Any styling I add as css doesn't seem to be added to the component styling when I inspect the element. I read through online and it seems to be suggesting the use of `/deep` and such. That also I tried and doesn't seem to fix the issue.

**Comment by harshit98** [comment]
@ajayns Okay. Change the PR name to `Addresses` by replacing `Fixes`. I will look into this issue.

**Comment by ajayns** [comment]
@harshit98 Any updates? How should I move forward?

**Pull request merged**
