### PR TITLE
Google like ui-implementation for smooth search interactions

### PR DESCRIPTION
**Pull request by hemantjadon**
* At first the search bar is in middle.

* Then as soon as user starts typing the page re-routes to the feed page (without url change), and the search request is completed there.

### CODE REVIEW

**Comment by daminisatya** [comment]
Would love to see the screenshots

**Comment by mariobehling** [comment]
Thank you.

This is related to issue: https://github.com/fossasia/loklak_search/issues/19

Please provide info on the related issue, screenshots and test page in future.

**Comment by hemantjadon** [comment]
@daminisatya 
Here is the Gif in working :)

google like

**Comment by mariobehling** [comment]
@hemantjadon It is working well. Next steps: Please match the height of the gray top bar to Google's bar and display the search results in the same design as Google. Please also use white as a background color and linkify links. Thank you.

**Pull request merged**
