### PR TITLE
Fixed #671 and #632:Resolved bugs with Service Box (Links work fine and Service box closes when clicked outside of it)

### LINKED ISSUE #671: links in service-box menu not working.
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
The links in service-box menu(top right corner) does not responds.The box collapses without taking us to the desired page.

**Expected behavior:**
Clicking on any of the components should take to the desired page.

**I would like to work on this:**

### PR DESCRIPTION
**Pull request by praveenojha33**
**Changes proposed in this pull request**
- Fixes #671 and #632 

**Screenshots (if appropriate)** 

**Link to live demo: ** http://pr-681-fossasia-loklaksearch.surge.sh

**Closes #671 and #632 **

### CODE REVIEW

**Comment by praveenojha33** [comment]
@ParthS007 @prshntsingh @vaibhavsingh97 Please review

**Comment by prshntsingh** [comment]
@praveenojha33 It solves the issue.But even I cannot figure out why code coverage is decreasing.Will you mind removing the "OnInit" module, even without that the code works fine.Something like this-
```
import { Component, ElementRef } from '@angular/core';

@Component({
	selector: 'service-box',
	templateUrl: './service-box.component.html',
	styleUrls: ['./service-box.component.scss'],
	host: {
'(document:click)': 'onClick($event)'
}
})

export class ServiceBoxComponent{
	public opened = false;
	onClick(event) {
if (!this._eref.nativeElement.contains(event.target)) {
	this.opened = false;
}
}
	constructor(private _eref: ElementRef) { }
}
```

**Comment by praveenojha33** [comment]
It is imported in Angular by default. I do not think removing this will make any difference on coverage.
Thanks for the review @prshntsingh

**Comment by prshntsingh** [comment]
@praveenojha33 please solve this issue ASAP 👍

**Comment by praveenojha33** [comment]
@simsausaurabh I tried to create tests for injecting `ElementRef` but when I test it.It says can't resolve all component of `ElementRef`, I have never written unit tests before, Can you please help me.

**Pull request merged**
