### PR TITLE
Addresses#639 Increase Accessibility audit

### PR DESCRIPTION
**Pull request by ParthS007**
**Changes proposed in this pull request**
- Buttons have an accessible name.
- Form element has associated labels.
- Page specifies the Valid language.
- Made `short_name` less than 12 characters in the manifest.

**Screenshots (if appropriate)** 
image

**Link to live demo: http://pr-645-fossasia-loklaksearch.surge.sh

Fixes partially #639

### CODE REVIEW

**Comment by ParthS007** [comment]
@singhpratyush  Please review. Thanks

**Comment by singhpratyush** [comment]
screenshot from 2018-01-21 10-53-13

This can be fixed too.

**Comment by ParthS007** [comment]
@singhpratyush  I tried to fix it but can't able to figure out, can you please help ?

**Comment by singhpratyush** [comment]
I think you just need to put a label on the element there - 
```html
<input ... label="my-label" >
```

**Comment by singhpratyush** [comment]
@ParthS007: Any updates on this?

**Pull request merged**
