### PR TITLE
Fixes #254 :- New search error

### LINKED ISSUE #254: New searches not always executed
If the user has performed one search and tries other searches, the searches are not always performed and the page with the new search does not load.

screenshot from 2017-02-03 11-47-49

### PR DESCRIPTION
**Pull request by Achint08**
Checkout gh-pages [here](https://achint08.github.io/loklak_search/).
Also I added condition for location and website since not every user provide location and website So I have added condition to avoid errors and search service crash due to undefined variable. 

Solves #254

### CODE REVIEW

**Comment by mariobehling** [comment]
@Achint08 Thank you. Previous merges resulted in PR conflicts. Please help to solve them.

**Comment by Achint08** [comment]
Done. :)

**Comment by uttu357** [comment]
@Achint08 Great.. :+1:  @mariobehling Can be merged.. :)

**Comment by hemantjadon** [comment]
Looks good to me 👍

**Pull request merged**
