### PR TITLE
Fixed discrepancies in contact form validation

### LINKED ISSUE #940: Contact form validation has discrepancies
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

The submit button is enabled event if email and phone number are not valid. 

**Expected behavior:**

Submit button should be enabled only if the email is a valid email and phone number is minimum 10-digit

**Screenshots of the issue:**

screenshot_2018-12-16 loklak search - distributed search for twitter and social media with peer to peer technology

**Will work on the issue??**

Yes, I'm working

### PR DESCRIPTION
**Pull request by shreyanshdwivedi**
**Changes proposed in this pull request**
- Fixed email validation in Contact form
- Fixed validation in contact number in Contact Form
- Fixed error messages

**Screenshots (if appropriate)** 
ezgif com-video-to-gif 3

**Link to live demo: ** http://pr-941-fossasia-loklaksearch.surge.sh

**Closes #940**

### CODE REVIEW

**Comment by shreyanshdwivedi** [comment]
@praveenojha33 @simsausaurabh please review

**Comment by shreyanshdwivedi** [comment]
@praveenojha33 @simsausaurabh please review :)

**Review by praveenojha33 — CHANGES_REQUESTED** [review]
The bottom of contact form is colliding with the footer. Also change minimum 100 words to 100 characters.
image

**Review by simsausaurabh — COMMENTED** [review]
Please complete the requested changes.

**Comment by shreyanshdwivedi** [comment]
@simsausaurabh @praveenojha33 I've made the changes. Please review :)

screenshot_2018-12-24 loklak search - distributed search for twitter and social media with peer to peer technology

**Review by simsausaurabh — APPROVED** [review]
@shreyanshdwivedi Changes look good as per the requirement of the current PR. But after submitting, the form should automatically close but it isn't working. Please look into it too. :+1:

**Comment by shreyanshdwivedi** [comment]
@simsausaurabh I've fixed it. Please take a look :))

**Comment by shreyanshdwivedi** [comment]
@praveenojha33 please review

**Comment by shreyanshdwivedi** [comment]
@praveenojha33 please review

**Review by praveenojha33 — APPROVED** [review]

**Comment by shreyanshdwivedi** [comment]
@simsausaurabh please merge

**Review by simsausaurabh — APPROVED** [review]

**Pull request merged**
