### PR TITLE
Fixes #320: Match distance above search bar on pages to market leader

### LINKED ISSUE #320: Match distance above search bar on pages to market leader
Above the search bar of the market leader the distance to the edge is smaller. Please match it and reduce the distance on loklak.

screenshot from 2017-03-30 19-50-58

screenshot from 2017-03-30 19-50-42

### PR DESCRIPTION
**Pull request by rishiraj824**
**Changes proposed in this pull request**
- Color of the search bar wrapper changed to #fafafa as the market leader.

**Screenshots** 
screenshot 88
screenshot 89
**Closes #320**

**Link** - [rishiraj824.github.io/loklak_search](http://rishiraj.co/loklak_search)

### CODE REVIEW

**Comment by uttu357** [comment]
@hemantjadon Should the color change be added as a separate PR after creating another issue as it is not part of the issue this PR aims to resolve? Otherwise looks good to me..

**Comment by hemantjadon** [comment]
@uttu357  I checked the google design they have their color to `#fafafa` so I think as far as matching design goes it should be done.
Also @rishiraj824 Working link will really be helpful :)

**Comment by uttu357** [comment]
@rishiraj824 Perform a rebase and remove merge commits from your pull request.. Also provide a working link.. :)

**Comment by rishiraj824** [comment]
@uttu357 Yes I'll do that. Was just fixing the suggestion box. :)

**Comment by rishiraj824** [comment]
@hemantjadon and @uttu357 Link Provided! Please review :)

 [rishiraj824.github.io/loklak_search](http://rishiraj.co/loklak_search)

**Comment by hemantjadon** [comment]
Looks good to me :)

**Pull request merged**
