### PR TITLE
Fixes #800: Setup new firebase auth providers - Facebook, Github, Google, Email/Password

### LINKED ISSUE #800: Setup new firebase auth providers - Facebook, Github, Google, Email/Passowrd
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**

Setup new projects on Github, Facebook and setup more firebase auth providers: Facebook, Github, Google, Email/Passowrd.

**Expected behavior:**

User should be able to login using any of these auth providers.

**Screenshots of the issue:**

### PR DESCRIPTION
**Pull request by simsausaurabh**
**Changes proposed in this pull request**
- Created new apps for ```loklak-search``` on Facebook and Github.
- Setup new auth providers - Facebook, Github, Google, Email/Password.

**Screenshots (if appropriate)** 

screenshot from 2018-06-29 19-08-25

**Link to live demo: http://pr-801-fossasia-loklaksearch.surge.sh**

**Closes #800**

### CODE REVIEW

**Comment by simsausaurabh** [comment]
@singhpratyush @praveenojha33 Please review.

**Comment by praveenojha33** [comment]
I am unable to login?
desktop-animation

**Comment by simsausaurabh** [comment]
@praveenojha33 This is because I haven't added this PR link in firebase console to allow login from. I have added it now, please review.

**Comment by simsausaurabh** [comment]
@praveenojha33 I am implementing new login component with all service providers and the current login button will then route to this login component. This patch is required for that. The issue of constant clicking of login button will then also get fixed since the user will be redirected to login route.

**Comment by praveenojha33** [comment]
@simsausaurabh I am unable to see other options to login, I am automatically getting redirected to login by twitter and I am getting logged in.

**Comment by simsausaurabh** [comment]
Actually I have not used those methods currently and kept login with twitter. But I have created a new login component and made a new route (```/login```) to that, I will create separate buttons and use them to login on this login component page. I have tested all these methods one bye one with this current login button. These methods will be used in new login component to provide all service providers at one place.

**Pull request merged**
