### PR TITLE
Implements #29 : Adds autocompletion suggestion feature

### PR DESCRIPTION
**Pull request by Achint08**
Implements auto completion feature. Checkout it out [here](https://achint08.github.io/loklak_search/).
Kindly review and correct me. :)
One more I would like to have a view is that I haven't use datalist element to show the suggestions reason being that the new suggesstion data was not displayed in that case. Any suggesstion?

### CODE REVIEW

**Comment by mariobehling** [comment]
Nice job!

Please avoid scroll bars.

screenshot from 2017-02-03 11-43-45

**Comment by Achint08** [comment]
@mariobehling Can you guide me regarding this because sometimes when there are many suggestions it kind of hides the tweets and overflows the page that's why i added scroll. Horizontal scroll bars will now not work but vertical is a must.

**Comment by mariobehling** [comment]
@Achint08 Google always shows between 4-6 suggestions. How can we replicated this without the scroll bars? The font and size of suggestions should also be the same as in the search bar.

screenshot from 2017-02-03 12-40-25

**Comment by Achint08** [comment]
@mariobehling Done. 

screen shot 2017-02-03 at 6 05 01 pm

**Comment by mariobehling** [comment]
Excellent job!

**Pull request merged**
