### PR TITLE
Align Settings Tab with Search Bar Fixes-#914

### LINKED ISSUE #914: Align Settings Tab with Search Bar
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
Currently the settings tab is on right side below search bar. 

**Expected behavior:**
Please align it with search bar.

**Screenshots of the issue:**
image

### PR DESCRIPTION
**Pull request by championpaddler**
**Changes proposed in this pull request**
- Aligning Settings Tab

**Screenshots (if appropriate)** 

screenshot from 2018-11-01 21-38-46

Link : https://pr-923-fossasia-LoklakSearch.surge.sh

**Closes #914 **

### CODE REVIEW

**Comment by championpaddler** [comment]
@praveenojha33  @simsausaurabh  Please review.

**Comment by praveenojha33** [comment]
Please mention the surge link for your changes. So that reviewers can review your PR easily.

**Comment by championpaddler** [comment]
> Please mention the surge link for your changes. So that reviewers can review your PR easily.

Here it is . https://pr-923-fossasia-LoklakSearch.surge.sh  . :smile:

**Comment by championpaddler** [comment]
@praveenojha33  Please review.

**Review by praveenojha33 — COMMENTED** [review]
It is not working for all screens. Please fix it for all screen sizes.
image

**Comment by praveenojha33** [comment]
Also there are some texts which are overlapping in sidebar. For which I have raised an issue here https://github.com/fossasia/loklak_search/issues/925 Can you please look into it. 
Thank You.

**Comment by championpaddler** [comment]
@prateekchaplot Can you please retry opening in private mode because it is working perfectly in my pc??

**Comment by championpaddler** [comment]
@praveenojha33  Demo https://vimeo.com/user91264543/review/298425736/b6d12d4aa4

**Comment by praveenojha33** [comment]
@praveenojha33 Please see in developer option for larger screens.
@simsausaurabh Please review it.

**Comment by championpaddler** [comment]
@praveenojha33 ok i will test for larger screens.

**Comment by championpaddler** [comment]
@simsausaurabh  Please review

**Comment by championpaddler** [comment]
@simsausaurabh  Please review.

**Comment by championpaddler** [comment]
@praveenojha33  Now it will work on large screens.

**Review by simsausaurabh — CHANGES_REQUESTED** [review]
@sk9331657 There are still some bugs, please see:

screenshot from 2018-11-06 17-49-45

**Comment by championpaddler** [comment]
@simsausaurabh  @praveenojha33  Now please  check it.

**Review by simsausaurabh — CHANGES_REQUESTED** [review]
There are still some issues, please see:

screenshot from 2018-11-15 14-35-50

screenshot from 2018-11-15 14-36-15

**Review by simsausaurabh — COMMENTED** [review]
@sk9331657 What is the update on this PR?

**Comment by simsausaurabh** [comment]
Please follow up, closing due to inactivity.

**Pull request closed without merging**
