### PR TITLE
Updating the badgeyay icon. #927

### LINKED ISSUE #927: Updating the badgeyay icon.
**I'm submitting a ...**
- [x] feature request

**Current behavior:**

Outdated icon.
**Expected behavior:**

Updating icon with latest one.

Will work on the issue??
Yes

### PR DESCRIPTION
**Pull request by championpaddler**
**Changes proposed in this pull request**
-Updated Icon

**Screenshots (if appropriate)** 

screenshot from 2018-11-02 13-28-47

**Link to live demo: http://pr-929-fossasia-loklaksearch.surge.sh

**Closes #927 **

### CODE REVIEW

**Comment by championpaddler** [comment]
@fossasia/loklak-devs Please review

**Comment by championpaddler** [comment]
@simsausaurabh  Please review.

**Review by abishekvashok — APPROVED** [review]

**Comment by championpaddler** [comment]
@Orbiter @simsausaurabh  @praveenojha33  This can be merged .

**Review by praveenojha33 — APPROVED** [review]
LGTM :+1:

**Review by simsausaurabh — APPROVED** [review]

**Pull request merged**
