### PR TITLE
FIxes #267: Fetch all instead of cached

### LINKED ISSUE #267: A number of searches do not display search results even though server provides results
I checked the result of from:MartinSchulz. If the user clicks on an @someaccount link on the search results, he/she will quickly discover a number of results that do not show up. Tests on http://api.loklak.org show results though.

screenshot from 2017-02-09 23-22-15

### PR DESCRIPTION
**Pull request by hemantjadon**
**Fixes #267:**

**Changes proposed in this pull request**

* Fetching all results insted of only cached enteries.

### CODE REVIEW

**Comment by Achint08** [comment]
@hemantjadon search service is crashing in this case. kindly revert the PR.

**Comment by hemantjadon** [comment]
Is not recieving aggregations has something to do with Backend??

**Comment by Achint08** [comment]
In api documentation it is written source must be set to cache. 

screen shot 2017-02-11 at 4 02 08 pm

So let's make another issue for this @hemantjadon .
One good thing that this PR is doing is that the pagination will work good after this. :)

**Comment by mariobehling** [comment]
It seems like the sidebar does not work anymore after the merge of this PR.

screenshot from 2017-02-11 13-17-52

**Pull request merged**
