### PR TITLE
Fixes #603 "Adding more icon links in the top right dropdown menu"

### LINKED ISSUE #603: Adding more icon links in the top right dropdown menu
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current Behaviour:**
Currently, the top right dropdown menu only contains the icon links of the major FOSSASIA projects. 

**Expected Behaviour:**
There should be more icon links like bug report, contact, code etc. in the dropdown menu.

**Screenshots of the issue:**
(Not applicable here)

**Would you like to work on this issue?**
Yes.

### PR DESCRIPTION
**Pull request by sudwebd**
**Changes proposed in this pull request**
- Added more icons to the top right dropdown menu
- Added proper links with the icons
- Added link to labs.fossasia.org

**Screenshots (if appropriate)
old
image
new
image

** 

**Link to live demo (if appropriate):** 

**Closes #**

### CODE REVIEW

**Comment by marvin08** [comment]
@sudwebd Please add a demo link as well in your PR.

**Comment by harshit98** [comment]
@sudwebd Kindly do the suggested changes:
- Add demo link (if possible) else screenshot looks good to me!
- Remove `package-lock.json`
- Squash your commits. Your PR should be only having 1 commit.

**Comment by mariobehling** [comment]
Thanks. 

* Please take out "Contact". 
* Add eventyay.

**Comment by sudwebd** [comment]
@mariobehling I have removed contact and added eventyay , I have put the updated image . Check if it looks good.

**Comment by sudwebd** [comment]
@harshit98 there were some issues while I was uploading to gh-pages ,I will try to provide the demo link , you can check the image, I have added the new image .

**Comment by sudwebd** [comment]
image
@harshit98 it is giving merge conflicts again and again when I am squashing the commits, help me out...

**Comment by mariobehling** [comment]
Closing this due to inactivity solving the Travis issue. Please reopen if possible.

**Pull request closed without merging**
