### PR TITLE
Fixes #42: Add related hashtags component

### LINKED ISSUE #42: Show related hashtags on bottom of search result page
On the bottom of search page results we often find "related searches". Please implement a similar thing "related hashtags".

screenshot from 2016-10-17 17 18 12

### PR DESCRIPTION
**Pull request by uttu357**
*Collect hashtags from the search results in decreasing order of frequency
*Display top 10 hashtags in the feed-footer

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks.

Could you deploy it on your repository, so we can see how it works.

Also please add a screenshot to the PR.

Cheers.

**Comment by uttu357** [comment]
screenshot from 2016-12-15 18 24 56

Sure will deploy it asap. :+1:

**Comment by hemantjadon** [comment]
This seems good Nice work @uttu357  👍

**Comment by uttu357** [comment]
Deployed [https://uttu357.github.io/loklak_search/search?query=amsterdam](https://uttu357.github.io/loklak_search/search?query=amsterdam)
You will need to enable loading of unsafe scripts as the api is on http and github pages are on https resulting in a mixed content warning.

**Comment by hemantjadon** [comment]
@uttu357 This search is not working throwing MixedContent error.

As gh-pages uses `https` and api uses `http` followup the thread here for more details
https://github.com/fossasia/loklak_search/issues/17

Well I can see that its working by "allowing unsafe scripts" and the code is working fine and PR can be merged. :)

**Comment by hemantjadon** [comment]
@uttu357 @mariobehling I think changes are good thus I am merging this.

@uttu357 Nice Work. Would you like to add some `unit tests` for this component.

**Comment by uttu357** [comment]
Sure Ill work on adding unit tests for this component.

**Pull request merged**
