### PR TITLE
Close suggest box after fetching query

### LINKED ISSUE #439: Suggestions staying even when search result is already being displayed
Please only show suggestions during typing. Compare it to Google, please.
screenshot from 2017-07-06 03-40-23

### PR DESCRIPTION
**Pull request by hemantjadon**
Closing suggest box after the the query is fetched.

* This makes sure that suggestion panel is closed after the results are fetched

https://hemantjadon.github.io/loklak_search

**Closes #439 **

### CODE REVIEW

**Comment by Achint08** [comment]
@hemantjadon Already. It seems to work fine. But please provide test link.

**Comment by hemantjadon** [comment]
@Achint08 Updated the test link

**Comment by Achint08** [comment]
@hemantjadon Please change your gh-pages API request address to your G-cloud deployment link so that review process goes fast.

**Comment by mariobehling** [comment]
Good job!

**Pull request merged**
