### PR TITLE
Fixes #795: Make responsive in smaller devices

### LINKED ISSUE #795: Distortion in responsiveness in smaller devices.
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
Currently,the views option is distorted in Mobile and devices of smaller screen sizes.
**Expected behavior:**
Fix the distortion by adjusting the views options. 
**Screenshots of the issue:**

image

### PR DESCRIPTION
**Pull request by simsausaurabh**
**Changes proposed in this pull request**
- Made responsive in small screen resolutions.

**Screenshots (if appropriate)** 

**Link to live demo: http://pr-799-fossasia-loklaksearch.surge.sh**

**Closes #795**

### CODE REVIEW

**Comment by simsausaurabh** [comment]
@praveenojha33 Please review.

**Comment by praveenojha33** [comment]
I think we have enough space between different tabs to show one more tab. Please show one more tab on mobile i.e Media Wall 
image

**Comment by simsausaurabh** [comment]
Thanks. I am fixing them :+1:

**Comment by mariobehling** [comment]
What is the status of this PR? Please finalize this.

**Comment by simsausaurabh** [comment]
Yes. I am currently working on it, will be fixed asap.

**Comment by simsausaurabh** [comment]
@praveenojha33 Please review.

**Comment by simsausaurabh** [comment]
@praveenojha33 Please review.

**Comment by simsausaurabh** [comment]
I will update this patch by tonight.

**Comment by simsausaurabh** [comment]
@praveenojha33 Please review. I have fixed all the alignment issues in various screen resolutions > 320px (Standard).

**Pull request merged**
