### PR TITLE
 Fixes #489: Restore view button on header

### LINKED ISSUE #489: Views button for media wall disappeared
The views button disappeared. I missed the PR and issue where this was proposed.

Please keep the standard design and re-add the news button. Take out the icon for media wall on the top right.
screenshot from 2017-07-25 10-52-37

Related to: https://github.com/fossasia/loklak_search/issues/450

### PR DESCRIPTION
**Pull request by Achint08**
**Changes proposed in this pull request**
- Restore view button on header

**Screenshots (if appropriate)** 
screen shot 2017-07-28 at 10 54 59 pm

**Link to live demo (if appropriate):** 

http://achint08.github.io/loklak_search/

**Closes #489 **

### CODE REVIEW

**Comment by Achint08** [comment]
@hemantjadon @SKrPl @vibhcool @kavithaenair @singhpratyush @djmgit  Please review.

**Comment by Achint08** [comment]
@singhpratyush Done! 👍 
Checkout now. 
https://achint08.github.io/loklak_search/

**Comment by singhpratyush** [comment]
@Achint08: It still happens when you select `Tools` first.

**Comment by Achint08** [comment]
@singhpratyush I think there is no issue in opening both the menu at once.

**Pull request merged**
