### PR TITLE
Fixes #914: Aligned settings tab

### LINKED ISSUE #914: Align Settings Tab with Search Bar
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
Currently the settings tab is on right side below search bar. 

**Expected behavior:**
Please align it with search bar.

**Screenshots of the issue:**
image

### PR DESCRIPTION
**Pull request by div12gau**
**Changes proposed in this pull request**
- Aligned Settings tab.

**Screenshots (if appropriate)** 
issue914

**Link to live demo: ** http://pr-916-fossasia-loklaksearch.surge.sh

**Closes #914**

### CODE REVIEW

**Review by singhpratyush — COMMENTED** [review]
This would work for a small segment of screen sizes only. Here is an example of it failing at 1920x1080 :point_down: 

pr-916-fossasia-loklaksearch surge sh_

**Review by praveenojha33 — CHANGES_REQUESTED** [review]
@div12gau Also please fix the alignment of options which appear after clicking the different tabs.
image

**Comment by simsausaurabh** [comment]
@div12gau Any updates on this PR?

**Comment by div12gau** [comment]
I'm not free this time so assign it to any other.

**Comment by div12gau** [comment]
@simsausaurabh  I'm not free this time so assign it to anyone.

**Review by simsausaurabh — CHANGES_REQUESTED** [review]
@div12gau Closing this due to inactivity, reopen it once done with changes. The issue is open to everyone :+1:

**Pull request closed without merging**
