### PR TITLE
Final fix for 404 error in image

### LINKED ISSUE #688: 404 Image Error in Media Wall
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
On going to the Media wall, switching the image filter to True and searching for a word, sometimes we receive a 404 error in place of the original image.

**Expected behavior:**
It should return the original image instead.

**Screenshots of the issue:**
screen shot 2018-03-18 at 5 15 03 am

I would like to work on this 😄

### PR DESCRIPTION
**Pull request by Remorax**
**Changes proposed in this pull request**
- This PR removes the 404 bug gotten in the first request made immediately on loading the page. I believe this PR should completely fix #688 

**Screenshots** 
BEFORE
screen shot 2018-03-19 at 4 28 14 am

AFTER
screen shot 2018-03-19 at 4 28 53 am

Test link: [https://pr-692-fossasia-LoklakSearch.surge.sh](https://pr-692-fossasia-LoklakSearch.surge.sh)

**Closes #688 **

### CODE REVIEW

**Comment by singhpratyush** [comment]
@Remorax: Please provide a test link.

**Comment by Remorax** [comment]
@singhpratyush  I have provided screenshots so that you can review. If a link is needed, can you suggest how I should resolve this Travis warning so that it gets deployed?

**Comment by praveenojha33** [comment]
@Remorax Use `ng lint --fix` to resolve it automatically if it can be resolved. Some linting errors might not get resolved by doing this than you have to resolve it manually. :+1:

**Comment by Remorax** [comment]
@singhpratyush I guess that got added due to #645 but I've removed it anyway 😄

**Comment by singhpratyush** [comment]
Good job. Let's wait for some more reviews.

**Comment by Remorax** [comment]
Um @kapillamba4 this fix is only for the media wall. On the normal search view, it works fine without the patch, but if you try the query `recommend puberty` on the media wall, on the website, you'll get a 404 error but if you pull my fork (since the media wall view for my test link doesn't work, it gives a surge error) and try the same query over there, it should work perfectly! 
I just checked it once again to be sure 😄

**Pull request merged**
