### PR TITLE
Fixes #561 Removed README.rst

### LINKED ISSUE #561: Remove redundant README.rst
## Description

The docs for this repo along with other loklak projects would be generated using yaydoc. Since it supports markdown format so `rst` format is no longer required.

### PR DESCRIPTION
**Pull request by pri22296**
**Changes proposed in this pull request**

- Removed README.rst

**Closes #561**

### CODE REVIEW

**Comment by pri22296** [comment]
@imujjwal96 @sch00lb0y Please review

**Comment by Achint08** [comment]
@imujjwal96 @pri22296 We need to add yaydocs.yml now.

**Comment by jigyasa-grover** [comment]
@Achint08 Create a new issue and follow up with a new PR. Thanks !

**Comment by pri22296** [comment]
@Achint08 The docs of this repo would be generated along with other loklak projects as a single website. Since the [dev.loklak.org](https://github.com/loklak/dev.loklak.org/blob/master/.yaydoc.yml) already has a `.yaydoc.yml`, we won't be needing it here.

**Pull request merged**
