### PR TITLE
Fixes #356 :- Change StoreDevtoolsModule used method

### LINKED ISSUE #356: Problem with deployment after upgrade
Local deployment not working after upgrade.

**Error given**
`Unhandled Promise rejection: can't convert undefined to object ; Zone: <root> ; Task: Promise.then ; Value: TypeError: can't convert undefined to object` .

### PR DESCRIPTION
**Pull request by Achint08**
**Changes proposed in this pull request**
- The issue is referenced here :- https://github.com/ngrx/store/issues/357

**Closes #356 **

### CODE REVIEW

**Comment by mariobehling** [comment]
@Achint08 Please ask and assign co-developers to review.

**Comment by Achint08** [comment]
@hemantjadon @rishiraj824  Kindly review. :)

**Comment by hemantjadon** [comment]
@Achint08 where is this bug coming? When you haven't installed store devtools ?

**Comment by Achint08** [comment]
@hemantjadon Installed it already still getting this error.

**Comment by Achint08** [comment]
@hemantjadon Can you tell me version of your installed store devtools ?

**Comment by hemantjadon** [comment]
@Achint08 ReduxDevtools Chrome Extension => 2.5.1
ngrx store devtools => latest

**Comment by Achint08** [comment]
@hemantjadon checkout [https://achint08.github.io/loklak_search/](https://achint08.github.io/loklak_search/) console.

**Comment by Achint08** [comment]
@hemantjadon I got the issue. So i was on v3.2.3 previously and v3.2.4 ( https://github.com/ngrx/store-devtools/pull/55 ) solves this issue. I wonder why npm didn't update me to the latest patch.

**Comment by hemantjadon** [comment]
@Achint08 Should this be closed then?

**Comment by Achint08** [comment]
@hemantjadon Sure.

**Pull request closed without merging**
