### PR TITLE
Improve top hashtags displayed on home page

### LINKED ISSUE #440: Improve Popular Hashtags on Start Page
1. Please document on the Readme how hashtags are chosen to being displayed on front page.
2. Ensure relevant popular tags are really displayed. Currently it seems the hashtags are not really relevant and there are only three.
3. In front of hashtags add text "Popular Hashtags:"

### PR DESCRIPTION
**Pull request by hemantjadon**
* Include new Redux state to store the trending hashtags

* Show the trening icon on the home page along with tooltip

**Link to live demo (if appropriate):** 
https://hemantjadon.github.io/loklak_search

**Closes #440 **

### CODE REVIEW

**Comment by mariobehling** [comment]
@singhpratyush :+1:

**Comment by hemantjadon** [comment]
@singhpratyush @mariobehling 
> Please document on the Readme how hashtags are chosen to being displayed on front page.
The hashtags are not chosen here they are are the aggregation results done on the basis of `aggregation` field `hashtags`, and whatever the list of results it gives, we display top 5.
Do we need to document which api endpoint results are fetched?

> In front of hashtags add text "Popular Hashtags:"
I have added an icon in front of the hashtags with a tooltip mentioning `trending hashtags`.
I guess it might be some caching issue because of which you are not able to see it. Please press `cmd + shift +R` to reset the cache.
IMHO a text like "Popular Hashtags" will not be a good idea that's why I created the tooltip.

**Comment by mariobehling** [comment]
> Do we need to document which api endpoint results are fetched?

The question is less about "chosen" and more the question: Please document the way things work.

> I have added an icon in front of the hashtags with a tooltip mentioning trending hashtags.

In this case, please use existing background colors - a lighter gray and avoid effects. Effects just give the impressions things are slow. Keep it fast please. Also increase the tool tip font size to match the size of text on the bottom bar.

**Comment by hemantjadon** [comment]
> avoid effects

@mariobehling the tooltip I used is in compliant to `Material Design Spec` and is implemented in `@angular/material`

>Effects just give the impressions things are slow

The animations will definitely run at 60fps so they will definitely be smooth.

>Also increase the tool tip font size to match the size of text on the bottom bar.

Will do it, the background color is light grey with an opacity.

**Pull request merged**
