### PR TITLE
Add commit message guidelines

### PR DESCRIPTION
**Pull request by uttu357**
The commit messages currently are varied because of lack of commit message guidelines. This PR hopes to resolve that by providing a set of guidelines for commit messages. This is taken from [angularJS Repository](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-git-commit-guidelines) and modified as needed.

### CODE REVIEW

**Comment by uttu357** [comment]
@mariobehling Please review.. :)

**Comment by Achint08** [comment]
hi @uttu357 PR is good and will serve the purpose.
You can also add PR Templates using https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/  so that template is created automatically. :)

**Comment by Achint08** [comment]
@uttu357 👍

**Comment by hemantjadon** [comment]
We can modify the further changes later if necessary 👍

**Pull request merged**
