### PR TITLE
Fixes #46: Implement news sub tab with results from news organizations

### LINKED ISSUE #46: Implement news sub tab with results from news organizations
Many news organizations have a twitter and youtube account. Please show a stream from news organization in the sub tab "News".

Implement as follows:
-  [ ] Create a json file with a list of accounts of social media of news organizations (sort alphabetically and by media, e.g. Twitter, Youtube)
-  [ ] Show the stream just like other search results in a sub tab "News"

screenshot from 2016-10-17 17 44 10

### PR DESCRIPTION
**Pull request by simsausaurabh**
**Changes proposed in this pull request**
- Adds a single news organisation(from:CNN) result. It is for testing and will be upgraded to more no of organisations taken from a json file.

**Screenshots (if appropriate)** 

**Link to live demo: http://pr-741-fossasia-loklaksearch.surge.sh** 

**Closes #46**

### CODE REVIEW

**Comment by simsausaurabh** [comment]
@hemantjadon please provide your suggestions on improvement. I am working on to create a new json/csv file and corresponding to each news organisation in json/csv file dispatch corresponding actions and get data from store for those queries. And at last calling ```feed-card``` with the ```apiResponse``` of result. Please guide me further.

**Comment by simsausaurabh** [comment]
@hemantjadon please review.

**Comment by praveenojha33** [comment]
Hello @simsausaurabh I think Travis is failing because some of the pre-written tests need to be modified. Please look into it.

**Comment by duttaditya18** [comment]
Travis has passed.

**Comment by simsausaurabh** [comment]
@singhpratyush Yes, when we search something like ```avengers``` we get the results normally. But after clicking on news tab it takes time to load news, since I have made it to load only when user clicks on news tab(I will fix it). And after that, when user tries to switch back to normal ```All``` or ```Images``` or ```Videos``` tab, the results come of news tab query(I will fix it). I had a doubt about the UI of news tab, so shall I keep it the same way as the normal views?

**Comment by simsausaurabh** [comment]
@singhpratyush @praveenojha33 please review. All the issues are fixed now.

**Comment by mariobehling** [comment]
@simsausaurabh It seems results are not limited to new organizations when I make multiple searches on the news tab. Please check.

screenshot from 2018-06-06 02-07-00

**Comment by simsausaurabh** [comment]
@mariobehling In order to search for top updated news every time when user clicks on ```News``` Tab, the news is made to load. The results of news take time to load. The main reason to not to load it beforehand are:
1. To provide updated latest news from news organizations.
2. To not to slow down the normal results in feeds in loklak (When user searches for any normal query).

This way user gets top news and user also doesn't face slow loading of results. A possible reason of getting other result apart from the news organization could be the slow loading of views. I am looking into it. Results are only displayed which have came from the news organizations. I am looking into the issues.

**Comment by praveenojha33** [comment]
Let other devs suggest their views on it.

**Comment by simsausaurabh** [comment]
@mariobehling I have added a JSON file with news organizations and fetching results according to it. I'l be updating the patch by today. :+1:

**Comment by mariobehling** [comment]
Read the branch policy that is there for a long time: https://github.com/fossasia/loklak_search/tree/development#branch-policy

**Pull request closed without merging**
