### PR TITLE
Fix-900 Add hardcoded LOGO URLs inside config file

### LINKED ISSUE #900: Add hardcoded LOGO URLs inside config file
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**

LOGO URLs are hardcoded.

**Expected behavior:**

They need to be added into the url config file.

**Screenshots of the issue:**

### PR DESCRIPTION
**Pull request by championpaddler**
**Changes proposed in this pull request**
- Add hardcoded LOGO URLs inside config file.

**Link to live demo: http://pr-928-fossasia-loklaksearch.surge.sh 

**Closes #900 **

### CODE REVIEW

**Comment by championpaddler** [comment]
@simsausaurabh  @praveenojha33  @daminisatya Please review.

**Comment by championpaddler** [comment]
@simsausaurabh @praveenojha33 @daminisatya @gabru-md @ParthS007  Please review.

**Comment by championpaddler** [comment]
@abishekvashok  @mariobehling  @hpdang Please review and merge this,

**Review by praveenojha33 — APPROVED** [review]
LGTM @simsausaurabh Please see if it is relevant.

**Review by simsausaurabh — CHANGES_REQUESTED** [review]
@sk9331657 The idea was to reduce the site load and make it more dynamic without storing actual images instead using image urls to display them. It would help in actually changing the config file for changing URLs through out the project.

**Comment by championpaddler** [comment]
@simsausaurabh  So the idea is to load all images from config url. Am I correct??

**Comment by championpaddler** [comment]
@simsausaurabh  Please review.

**Comment by championpaddler** [comment]
@simsausaurabh  @praveenojha33  Please review this also.

**Comment by championpaddler** [comment]
@simsausaurabh  Please review this .

**Comment by simsausaurabh** [comment]
@sk9331657 The idea was to use URLs of those logos deployed somewhere else. @mariobehling please provide your views on this issue.

**Comment by championpaddler** [comment]
@simsausaurabh  but hosting images on free platforms  may cause them to go down .

**Comment by championpaddler** [comment]
@simsausaurabh  @praveenojha33  Please update  what should be done.

**Comment by championpaddler** [comment]
@simsausaurabh @praveenojha33 Please review now.

**Comment by simsausaurabh** [comment]
@mariobehling Please provide your views on this issue.

**Review by mariobehling — APPROVED** [review]

**Comment by mariobehling** [comment]
Yes, I think this is a good approach and makes the system more generic. Thank you!

**Pull request merged**
