### PR TITLE
Fixes #634: Migrate: http->https

### LINKED ISSUE #634: Migrating from 'http' to 'https'
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

Few of the links in the project still serve on 'http'

**Expected behavior:**

Links to website should serve on 'https'

**Screenshots of the issue:**

### PR DESCRIPTION
**Pull request by simsausaurabh**
**Changes proposed in this pull request**
- Migrating from 'http' to 'https'

**Screenshots (if appropriate)** 

**Link to live demo (if appropriate):** 

**Closes #**
Closes #634

### CODE REVIEW

**Comment by Achint08** [comment]
Please deploy and provide a working link.

**Comment by simsausaurabh** [comment]
Deployment link:
https://pr-635-fossasia-loklaksearch.surge.sh/

**Comment by Achint08** [comment]
Good job!

**Comment by simsausaurabh** [comment]
Thank you :smile:

**Pull request merged**
