### PR TITLE
Adds tests for media-wall-custom background, card, header components

### PR DESCRIPTION
**Pull request by shreyanshdwivedi**
**Changes proposed in this pull request**
- Adds tests for media-wall-custom background, card, header components
- All the three components required testing of functions

screenshot_2019-02-04 code coverage report for all files

**Link to live demo: ** 
http://pr-954-fossasia-loklaksearch.surge.sh

**Related to #951**

### CODE REVIEW

**Comment by shreyanshdwivedi** [comment]
@praveenojha33 @simsausaurabh please review

**Review by simsausaurabh — APPROVED** [review]

**Comment by shreyanshdwivedi** [comment]
@praveenojha33 please review

**Comment by shreyanshdwivedi** [comment]
@praveenojha33 please review.

**Comment by simsausaurabh** [comment]
@praveenojha33 Please provide your review.

**Comment by shreyanshdwivedi** [comment]
@praveenojha @mariobehling please review

**Review by praveenojha33 — APPROVED** [review]

**Comment by shreyanshdwivedi** [comment]
@simsausaurabh please merge :)

**Comment by shreyanshdwivedi** [comment]
@simsausaurabh please merge.

**Pull request merged**
