### PR TITLE
Fixes #804: Create login with email and password through firebase

### LINKED ISSUE #804: Create login with email and password through firebase
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**

Currently user is only able to signup with email and password.

**Expected behavior:**

Provide new method for login with email and password through firebase.

**Screenshots of the issue:**

### LINKED ISSUE #808: Create a Angular snack-bar for messages/status of login/sign-up on login route
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**

Currently all errors/messages are printed on console for login/sign-up page.

**Expected behavior:**

There should be Angular snack-bar which should popup on every message/error on login/sign-up page with the status message.

**Screenshots of the issue:**

### PR DESCRIPTION
**Pull request by simsausaurabh**
**Changes proposed in this pull request**
- Created new method for login with email and password through firebase.
- Added new button for login in ```login``` route.
- Improved UI to match market standards.
- Added hover on buttons.
- Created Angular SnackBar to display status/messages related to login/signup.
**Screenshots (if appropriate)** 

screenshot from 2018-07-09 01-00-27

**Link to live demo: http://pr-805-fossasia-loklaksearch.surge.sh**

**Closes #804**
**Closed #808**

### CODE REVIEW

**Comment by simsausaurabh** [comment]
@mariobehling @singhpratyush @praveenojha33 Please review.

**Comment by simsausaurabh** [comment]
@mariobehling I have updated the UI, and tried to keep it similar/better with the standards. Please review:

screenshot from 2018-07-02 14-31-57

Since, the changes are major, I would like to send another patch for features like: instead of logging messages  on console, I will use material snackbar which is more of a standard. And will add methods for forgot password and reset password too.

**Comment by mariobehling** [comment]
Please delay this until we actually have features that require a login.

**Comment by simsausaurabh** [comment]
@mariobehling @praveenojha33 Closing this PR, until we actually have features to use login. I will send another patch for the same in future.

**Pull request closed without merging**
