### PR TITLE
Added tests for feed component

### PR DESCRIPTION
**Pull request by shreyanshdwivedi**
**Changes proposed in this pull request**
- Added tests for feed component to increase coverage

**Link to live demo: ** 
http://pr-943-fossasia-loklaksearch.surge.sh

**Related to #414**

### CODE REVIEW

**Review by simsausaurabh — APPROVED** [review]

**Comment by shreyanshdwivedi** [comment]
@simsausaurabh I'll open PR adding tests for each of the feed components. 
I have added all the tests which I could possibly do for this. Please merge this so that I can move further :))

**Comment by simsausaurabh** [comment]
Let more developers review too.

**Review by sakshee-19 — APPROVED** [review]

**Comment by shreyanshdwivedi** [comment]
@praveenojha33 please review

**Review by praveenojha33 — APPROVED** [review]

**Comment by shreyanshdwivedi** [comment]
@simsausaurabh please merge

**Review by simsausaurabh — APPROVED** [review]

**Pull request merged**
