### PR TITLE
autoscroll when bottom links clicked (added to all pages)

### PR DESCRIPTION
**Pull request by Achint08**
Solved #85. This time a better solution. Do review it.

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks. 

Could you show how it works on your repository?

Currently Travis is failing. Please check.

**Comment by Achint08** [comment]
Hello @mariobehling How to show it?
Should I add screenshots?

**Comment by mariobehling** [comment]
@Achint08 Could you deploy the system on your gh-pages?

Please check travis still failing.

**Comment by Achint08** [comment]
I am working on it. The error shown by travis CI is that "Failed: Error in ./AppComponent class AppComponent_Host - inline template:0:0 caused by: No provider for Router!" .  I need to import provider. I am working on it. I am going through some angular RC version problem. Will correct it soon.

**Comment by hemantjadon** [comment]
@achint08 @mariobehling 
this seems to be a reasonable solution right now and can be implemented for the current simple system. The tests may be failing due to not adding `RoutersStub` to `app.component.spec.ts` see add the required Stub in `app/testing/router-stubs.ts` See ` service stubs` in Angular's testing documentation.

The major concern which I am  using this approach is that it forces us to use scroll to top whenever the route changes which may not be the desired behavior. 
Consider the situation when user scrolls down to bottom of a long list and clicks a link which changes route, now if the user clicks on back button he will have to start scrolling from top again. 
Apparently I am not able to think of any solution which will solve both problems.

**Comment by Achint08** [comment]
The new error that is there is "TypeError: Cannot read property 'subscribe' of undefined". I researched about this. Couldn't get some solution. Please guide me with this.

**Comment by Achint08** [comment]
I would make a new pull request as soon I will fix this.This will take time I think. Thank you.

**Pull request closed without merging**
