### PR TITLE
Home page layout with search bar events to handle queries

### PR DESCRIPTION
**Pull request by hemantjadon**
Mainly the include of search service : 

Provides the api data to the view that requests it.

[TODOS] : 

* Add Tests for the service.

* Making a modeled structure for the request search params. (sources, fields, maximumRecords etc)

### CODE REVIEW

**Comment by mariobehling** [comment]
@hemantjadon Thank you. Let's follow best practices. Please match each pull request with an issue. Which issue does this PR solve?

Also the Angular1 version does not have any feature yet. Please make the PR to the gh-pages branch and make Angular 2 the standard.

Please also fix failing tests, if possible.

Thank you.

**Comment by hemantjadon** [comment]
@mariobehling 
* Definitely i will map PR to the Issue it solves.

* I am not able to understand what is meant by making angular2 standard, isn't it already on `gh-pages` of the repository ?

* Also I will look into the Failing build issue.

**Comment by mariobehling** [comment]
> I am not able to understand what is meant by making angular2 standard, isn't it already on gh-pages of the repository ?

Ok, good then. Yes, looks like it is done now. Cheers.

**Comment by daminisatya** [comment]
@hemantjadon looks like you are missing JSONP providers

**Comment by hemantjadon** [comment]
@daminisatya 
* I think all the tests are now passing and the changes are ready for merging.

* Can you please guide me about squashing the commits ?

**Comment by daminisatya** [comment]
@hematjadon  i have already addressed the same question. Please refer this pull request. https://github.com/fossasia/susi_android/pull/83

**Comment by hemantjadon** [comment]
I think i have created more commits then i have squashed.

I was unaware that i do not need to commit after every rebase conflict resolution.

What can be done now

**Comment by hemantjadon** [comment]
* I think i have squashed all commits into one.

* And this branch is ready for merging

Thanks for the help @daminisatya

**Comment by mariobehling** [comment]
Thank you. Please check failing checks and resolve. Cheers.

**Comment by hemantjadon** [comment]
* Issue was in the indentation of .circle.yml --> now fixed.

**Comment by hemantjadon** [comment]
@daminisatya 
Please merge this branch if everything feels good according to you.

**Comment by daminisatya** [comment]
Thanks for the patch ☺

**Pull request merged**
