### PR TITLE
Fixes #313 , #308 :-

### LINKED ISSUE #313: Start Page: Show top hashtags from last 24 hours
Instead of "Distributed Social Media Message Search Engine" display an area with the top hashtags of the last 24 hours (in simple text style).

Show 12 hashtags here as a link.

screenshot from 2017-03-30 15-05-35

### PR DESCRIPTION
**Pull request by Achint08**
**Changes proposed in this pull request**
Fixes #313 , #308 :-
- Added information of bug tracker in no result page
- showing top hashtags on home page
-  some minor bug fixes related to access specifiers

**Link to live demo (if appropriate):**
 [https://achint08.github.io/loklak_search/](https://achint08.github.io/loklak_search/)

** Issues faced**

HTML rendering is slow. That is the reason display of top hashtags takes time.
@hemantjadon Please review. :)

### CODE REVIEW

**Comment by hemantjadon** [comment]
> HTML rendering is slow. That is the reason display of top hashtags takes time.

Can't understand this is taking over 3 minutes ?? There is something else going on here. Please check. I will have a look at this.

**Comment by kavithaenair** [comment]
@Achint08 every query I type in the search shows no results.
For eg:
https://achint08.github.io/loklak_search/search?query=fossasia

**Comment by Achint08** [comment]
@kavithaenair Hey! Just click on this "Disable protection for now" . :)
screen shot 2017-06-10 at 3 29 41 am

**Comment by Achint08** [comment]
Closing PR for the time being. Will make soon another PR regarding this.

**Pull request closed without merging**
