### PR TITLE
Set titles dynamically on each query

### LINKED ISSUE #456: Change titles of page dynamically on each query
**Parent Issue #311**

* Use title service to do so
* Will also require Unit Tests to do so.

* [ ] Use basic service to update title 
* [ ] Write test

### PR DESCRIPTION
**Pull request by hemantjadon**
**Changes proposed in this pull request**

* Using title service for changing titles dynamically on every search

https://hemantjadon.github.io/loklak_search

**Closes #456**

### CODE REVIEW

**Comment by hemantjadon** [comment]
@Achint08 Yeah I was waiting for the other PR to merge that's why. Updated the link now

**Comment by hemantjadon** [comment]
@singhpratyush are the results shown? I mean if there is 502 bad gateway then the titles will not change, as they only change for successful search.

**Comment by vibhcool** [comment]
@hemantjadon , if there are no results shown, could there be change in title like for query car , `car-no result`

**Comment by hemantjadon** [comment]
@vibhcool Okay 👍  Will do it

**Comment by vibhcool** [comment]
@hemantjadon may be `car - no results` will be more useful

**Comment by hemantjadon** [comment]
@singhpratyush @vibhcool I have updated it to set titles as `<query>-Loklak Search-No Results` if no results are found. Please check.

**Pull request merged**
