### PR TITLE
Add https to startpage

### LINKED ISSUE #594: hashtags on start page not displayed
The hashtags on the startpage don't seem to use https and therefore no hashtags show up on the start page.

### PR DESCRIPTION
**Pull request by armen-gabrielyan**
**Changes proposed in this pull request**
- Added https so that hashtags show up on the home page

**Screenshots (if appropriate)** 
screenshot from 2017-11-23 00-53-34

**Closes #594**

### CODE REVIEW

**Comment by singhpratyush** [comment]
@ArmenGabrielyan16: The issue is not related to loklak.org. It is from loklak server itself.

Checkout this response - https://api.loklak.org/api/search.json?q=since:2017-11-23_00:00&callback=__ng_jsonp__.__req0.finished&minified=true&source=cache&maximumRecords=0&timezoneOffset=-330&startRecord=1&fields=hashtags&limit=10.

**Comment by harshit98** [comment]
Hi @ArmenGabrielyan16 What's the status of this PR ?

**Comment by ArmenGabrielyan16** [comment]
@harshit98 Hi. I would like to get some help to proceed. Thanks.

**Comment by mariobehling** [comment]
Thanks! This is resolved.

**Pull request closed without merging**
