### PR TITLE
Fix #256: Add followers page

### LINKED ISSUE #256: Implement a search page for account followers and following
The from:account search already offers a sidebar showing the top followers and following. Please implement a page doing the same.

Define a search pattern that needs to be entered into the search bar to find followers of a certain account. What would be the most appropriate?

### PR DESCRIPTION
**Pull request by uttu357**
**Changes proposed in this pull request**
- Add user card to the feed component
- Implement followers page using infinite scrolling to display vast no. of results
- Link to appropriate queries from the user card.
- **Fix footer error climbing to the side of the page**

**Screenshots (if appropriate)** 
screenshot from 2017-02-12 23 31 35

**Link to live demo (if appropriate):https://uttu357.github.io/loklak_search/search?query=followers:heroku** 

**Closes #256**

@mariobehling Please review and suggest changes if any! :)

### CODE REVIEW

**Comment by uttu357** [comment]
@hemantjadon Instead of adding on click loading i kept it infinite and loaded the items preemptively as the user is about to reach the end of the page. This will be better as the user has to click less... twitter also implements the followers page the same way.. Also i changed to use [API] for the actions.
Please review and suggest changes if any! :)

**Comment by hemantjadon** [comment]
@uttu357 if you want to keep infinite scroll make sure to show up a spinner while the results are loading, and also there is little jank and partially styled content which comes up, make sure it doesn't.

**Comment by uttu357** [comment]
@hemantjadon I changed it to click based pagination, as to detect loading of images i had to add event listeners to each image which were listened to by the feed component, which considerably slowed down the site.. Please review.. 
https://uttu357.github.io/loklak_search/search?query=followers%3Afossasia

**Comment by Achint08** [comment]
@uttu357 Please Add the syntax to search for followers at the home page 

screenshot from 2017-02-27 02 27 36

**Comment by uttu357** [comment]
@Achint08 Done! :)

**Comment by hemantjadon** [comment]
@uttu357 Hi,
This LGTM, can you point out the where you are doing the Event Listeners as I was not able to find them :P so that we can see what can be done.

I was also not able to review coz of the Exams are Going on. Sorry .

**Comment by uttu357** [comment]
i removed them as i was using them while trying to do infinite scrolling..

**Comment by Achint08** [comment]
@hemantjadon It was due to some problem on server side.
Now it is working fine.

**Comment by mariobehling** [comment]
Nice work! Working, so I am merging. Thank you.

**Pull request merged**
